<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

final class Fancelet_BIB1Seeder extends Seeder
{
	protected $galleryTable = 'fancelet_content_gallery';
	protected $textsTable = 'fancelet_content_texts';

	//    private array $verse = [
	//        91 => [
	//            'en_EN' => 'Isaiah 6 - Then I heard the voice of the Lord saying, "Whom shall I send, and who will go for us?" And I said, "Here am I; send me!"',
	//            'es_ES' => 'Isaías 6 - Escuché entonces la voz del Señor que decía: “¿A quién enviaré? ¿Quién irá de parte mía?” Yo le respondí: “Aquí estoy, Señor, envíame”.',
	//        ],
	//        92 => [
	//            'en_EN' => 'Psalm 138 - Though the Lord be high, he cares for the lowly; he perceives the haughty from afar.',
	//            'es_ES' => 'Salmo 138 - Aunque el Señor es excelso, cuida de los humilde, y al altivo reconoce desde lejos.',
	//        ],
	//        93 => [
	//            'en_EN' => 'Isaiah 6 - The seraph touched my mouth with it and said: "Now that this has touched your lips, your guilt has departed and your sin is blotted out".',
	//            'es_ES' => 'Isaías 6 - Con la brasa me tocó la boca, diciéndome: “Mira: Esto ha tocado tus labios. Tu iniquidad ha sido quitada y tus pecados están perdonados”.',
	//        ],
	//    ];
	//
	//    private array $explanation = [
	//        91 => [
	//            'en_EN' => 'This verse highlights the willingness to serve the Lord, showing a heart devoted and ready to fulfill His calling. Responding "Here I am" demonstrates faith and courage to act as an instrument of God’s will.',
	//            'es_ES' => 'Este versículo resalta la disposición a servir al Señor, mostrando un corazón entregado y dispuesto a cumplir su llamada. Responder "Aquí estoy" demuestra fe y valentía para actuar como instrumento de la voluntad divina.',
	//        ],
	//        92 => [
	//            'en_EN' => 'God, despite His greatness, lovingly attends to the humble and recognizes the pride of the arrogant. This psalm invites us to live humbly, trusting in His care, while avoiding the pride that distances us from His grace.',
	//            'es_ES' => 'Dios, a pesar de su grandeza, atiende con amor a los humildes y reconoce la altivez de los orgullosos. Este salmo nos invita a vivir con humildad, confiando en su cuidado, mientras evitamos el orgullo que nos aleja de su gracia.',
	//        ],
	//        93 => [
	//            'en_EN' => 'God purifies and forgives, renewing the soul of those who sincerely approach Him. This act of grace demonstrates His power to transform lives, preparing us to fulfill His purpose with a clean and reconciled heart.',
	//            'es_ES' => 'Dios purifica y perdona, renovando el alma de quienes se acercan a Él con sinceridad. Este acto de gracia muestra su poder para transformar vidas, preparándonos para cumplir su propósito con un corazón limpio y reconciliado.',
	//        ],
	//    ];


	private array $verse = [
		34 => ['es_ES' => 'Isaías 6 - Escuché entonces la voz del Señor que decía: “¿A quién enviaré? ¿Quién irá de parte mía?” Yo le respondí: “Aquí estoy, Señor, envíame”.', 'en_EN' => 'Isaiah 6 - Then I heard the voice of the Lord saying, "Whom shall I send, and who will go for us?" And I said, "Here am I; send me!"'],
		35 => ['es_ES' => 'Salmo 138 - Aunque el Señor es excelso, cuida de los humilde, y al altivo reconoce desde lejos.', 'en_EN' => 'Psalm 138 - Though the Lord be high, he cares for the lowly; he perceives the haughty from afar.'],
		36 => ['es_ES' => 'Isaías 6 - Con la brasa me tocó la boca, diciéndome: “Mira: Esto ha tocado tus labios. Tu iniquidad ha sido quitada y tus pecados están perdonados”.', 'en_EN' => 'Isaiah 6 - The seraph touched my mouth with it and said: "Now that this has touched your lips, your guilt has departed and your sin is blotted out".'],
		37 => ['es_ES' => 'Lucas 5 - Cuando acabó de hablar, dijo a Simón: “Lleva la barca mar adentro y echen sus redes para pescar”. Simón replicó: “Maestro, hemos trabajado toda la noche y no hemos pescado nada; pero, confiado en tu palabra, echaré las redes”. Así lo hizo y cogieron tal cantidad de pescados, que las redes se rompían. ', 'en_EN' => 'Luke 5 - When he had finished speaking, he said to Simon, "Put out into the deep water and let down your nets for a catch." Simon answered, "Master, we have worked all night long but have caught nothing. Yet if you say so, I will let down the nets". When they had done this, they caught so many fish that their nets were beginning to break.'],
		38 => ['es_ES' => 'Salmo 138 - Cuando te invoqué, Señor, me escuchaste. Aumentaste mis fuerzas dentro de mí.', 'en_EN' => 'Psalm 138 - When I called, you answered me; you increased my strength within me.'],
		39 => ['es_ES' => 'Corintios 15 - Por la gracia de Dios, soy lo que soy, y su gracia no ha sido estéril en mí; al contrario, he trabajado más que todos ellos, aunque no he sido yo, sino la gracia de Dios, que está conmigo..', 'en_EN' => 'Corinthians 15 - But by the grace of God I am what I am, and his grace toward me has not been in vain. On the contrary, I worked harder than any of them--though it was not I, but the grace of God that is with me. '],
		40 => ['es_ES' => 'Lucas 5 - Simón Pedro se arrojó a los pies de Jesús y le dijo: “¡Apártate de mí, Señor, porque soy un pecador!” Entonces Jesús le dijo a Simón: “No temas; desde ahora serás pescador de hombres”. Luego llevaron las barcas a tierra y, dejándolo todo, lo siguieron.', 'en_EN' => 'Luke 5 - But when Simon Peter saw it, he fell down at Jesus\' knees, saying, "Go away from me, Lord, for I am a sinful man!"  Then Jesus said to Simon, "Do not be afraid; from now on you will be catching people". When they had brought their boats to shore, they left everything and followed him.'],
		41 => ['es_ES' => 'Jeremίas 17 - Maldito el hombre que confía en el hombre, que en él pone su fuerza y aparta del Señor su corazón. Vivirá en la aridez del desierto, en una tierra salobre e inhabitable.', 'en_EN' => 'Jeremiah 17 - Cursed are those who trust in mere mortals and make mere flesh their strength, whose hearts turn away from the Lord. They shall live in the parched places of the wilderness, in an uninhabited salt land.'],
		42 => ['es_ES' => 'Lucas 6 - Dichosos serán ustedes cuando los hombres los aborrezcan y los expulsen de entre ellos, y cuando los insulten y maldigan por causa del Hijo del hombre. Alégrense ese día y salten de gozo, porque su recompensa será grande en el cielo. ', 'en_EN' => 'Luke 6 - Blessed are you when people hate you, and when they exclude you, revile you, and defame you on account of the Son of Man. Rejoice in that day and leap for joy, for surely your reward is great in heaven.'],
		43 => ['es_ES' => 'Corintios 1 - ¿Cómo es que algunos de ustedes andan diciendo que los muertos no resucitan? Porque si los muertos no resucitan, tampoco Cristo resucitó. Y si Cristo no resucitó, vana es nuestra fe.', 'en_EN' => 'Corinthians 1 - How can some of you say there is no resurrection of the dead? If there is no resurrection of the dead, then Christ has not been raised; and if Christ has not been raised, then your faith has been in vain.'],
		44 => ['es_ES' => 'Jeremías 17 - Bendito el hombre que confía en el Señor y en él pone su esperanza. Será como un árbol plantado junto al agua, que hunde en la corriente sus raíces; cuando llegue el calor, no lo sentirá y sus hojas se conservarán siempre verdes.', 'en_EN' => 'Jeremiah 17 - Blessed are those who trust in the Lord, whose trust is the Lord. They shall be like a tree planted by water, sending out its roots by the stream. It shall not fear when heat comes, and its leaves shall stay green.'],
		45 => ['es_ES' => 'Lucas 6 - ¡Ay de ustedes, cuando todo el mundo los alabe, porque de ese modo trataron sus padres a los falsos profetas!', 'en_EN' => 'Luke 6 - Woe to you when all speak well of you, for that is what their ancestors did to the false prophets.'],
		46 => ['es_ES' => 'Corintios 1 - Si nuestra esperanza en Cristo se redujera tan sólo a las cosas de esta vida, seríamos los más infelices de todos los hombres. Pero no es así, porque Cristo resucitó, y resucitó como la primicia de todos los muertos.', 'en_EN' => 'Corinthians 1 - If for this life only we have hoped in Christ, we are of all people most to be pitied. But in fact Christ has been raised from the dead, the first fruits of those who have died.'],
		47 => ['es_ES' => 'Lucas 6 - Dichosos ustedes los pobres, porque de ustedes es el Reino de Dios. Dichosos ustedes los que ahora tienen hambre, porque serán saciados. Dichosos ustedes los que lloran ahora, porque al fin reirán.', 'en_EN' => 'Luke 6 - Blessed are you who are poor, for yours is the kingdom of God. Blessed are you who are hungry now, for you will be filled. Blessed are you who weep now, for you will laugh.'],
		48 => ['es_ES' => '1 Corintios 15 - Hermanos, la Escritura dice que el primer hombre, Adán, fue un ser que tuvo vida; el último Adán es espíritu que da la vida. ', 'en_EN' => '1 Corinthians 15 - Thus it is written, "The first man, Adam, became a living being"; the last Adam became a life-giving spirit. But it is not the spiritual that is first, but the physical, and then the spiritual. '],
		49 => ['es_ES' => 'Lucas 6 - Traten a los demás como quieran que los traten a ustedes; porque si aman sólo a los que los aman, ¿qué hacen de extraordinario? También los pecadores aman a quienes los aman. Si hacen el bien sólo a los que les hacen el bien, ¿qué tiene de extraordinario?', 'en_EN' => 'Luke 6 - Do to others as you would have them do to you. If you love those who love you, what credit is that to you? For even sinners love those who love them. If you do good to those who do good to you, what credit is that to you?'],
		50 => ['es_ES' => 'Génesis 45 - Entonces José dijo a sus hermanos: no os entristezcáis ni os pese haberme vendido aquí. Pues para preservar vidas me envió Dios delante de vosotros.', 'en_EN' => 'Genesis 45 - Then Joseph said to his brothers: and now do not be distressed, or angry with yourselves, because you sold me here; for God sent me before you to preserve life.'],
		51 => ['es_ES' => 'Salmo 37 - No te irrites, porque sólo conduce al mal. Porque los malhechores serán destruidos, pero los que esperan en el Señor poseerán la tierra.', 'en_EN' => 'Psalm 37 - Do not fret yourself, it leads only to evil. For evildoers shall be cut off, but those who wait upon the Lord shall possess the land.'],
		52 => ['es_ES' => 'Lucas 6 - Sean misericordiosos, como su Padre es misericordioso. No juzguen y no serán juzgados; no condenen y no serán condenados; perdonen y serán perdonados. ', 'en_EN' => 'Luke 6 - Be merciful, just as your Father is merciful. Do not judge, and you will not be judged; do not condemn, and you will not be condemned. Forgive, and you will be forgiven.'],
		53 => ['es_ES' => '1 Corintios 15 - El primer hombre, hecho de tierra, es terreno; el segundo viene del cielo. Y del mismo modo que fuimos semejantes al hombre terreno, seremos también semejantes al hombre celestial.', 'en_EN' => '1 Corinthians 15 - The first man was from the earth, a man of dust; the second man is from heaven. Just as we have borne the image of the man of dust, we will also bear the image of the man of heaven.'],
		54 => ['es_ES' => 'Lucas 6 - En aquel tiempo, Jesús dijo a sus discípulos: “Amen a sus enemigos, hagan el bien a los que los aborrecen, bendigan a quienes los maldicen y oren por quienes los difaman.', 'en_EN' => 'Luke 6 - Jesus said, "I say to you that listen, Love your enemies, do good to those who hate you, bless those who curse you, pray for those who abuse you.'],
		55 => ['es_ES' => 'Salmo 99 - Exaltad al Señor nuestro Dios, y postraos ante el estrado de sus pies; Él es santo.', 'en_EN' => 'Psalm 99 - Proclaim the greatness of the Lord our God and fall down before his footstool; he is the Holy One.'],
		56 => ['es_ES' => 'Lucas 9 - De la nube surgió una voz que decía: "Éste es mi Hijo, mi Elegido; escúchenlo".', 'en_EN' => 'Luke 9 - Then from the cloud came a voice that said, "This is my Son, my Chosen; listen to him!" '],
		57 => ['es_ES' => 'Salmo 99 - Moisés y Aarón estaban entre sus sacerdotes, y Samuel entre los que invocaron su nombre; ellos clamaron al Señor, y Él les respondió.', 'en_EN' => 'Psalm 99 - Moses and Aaron among his priests, and Samuel among those who call upon his Name, they called upon the Lord, and he answered them.'],
		58 => ['es_ES' => '2 Corintios 3 - El Señor es el Espíritu, y donde está el Espíritu del Señor, allí hay libertad. Y todos nosotros, con el rostro descubierto, contemplando como en un espejo la gloria del Señor, nos vamos transformando en la misma imagen de gloria.', 'en_EN' => '2 Corinthians 3 - Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom. And all of us, with unveiled faces, seeing the glory of the Lord as though reflected in a mirror, are being transformed into the same image from one degree of glory.'],
		59 => ['es_ES' => 'Lucas 9 - "¡Oh generación incrédula y perversa! ¿Hasta cuándo he de estar con vosotros y os he de soportar?" Pero Jesús reprendió al espíritu inmundo, y sanó al muchacho y se lo devolvió a su padre. ', 'en_EN' => 'Luke 9 - "You faithless and perverse generation, how much longer must I be with you and bear with you?" But Jesus rebuked the unclean spirit, healed the boy, and gave him back to his father.'],
		60 => ['es_ES' => 'Salmo 99 - Oh Señor, Dios nuestro, tú les respondiste; fuiste para ellos un Dios perdonador.', 'en_EN' => 'Psalm 99 - O Lord our God, you answered them indeed; you were a God who forgave them.'],
		61 => ['es_ES' => 'Lucas 9 - Dos hombres hablaban con Él, Moisés y Elías. Pedro y sus compañeros estaban agotados por el sueño, pero como habían permanecido despiertos, vieron la gloria de Jesús.', 'en_EN' => 'Luke 9 - Suddenly they saw two men, Moses and Elijah. Now Peter and his companions were weighed down with sleep; but since they had stayed awake, they saw the glory of Jesus.'],
		62 => ['es_ES' => 'Deuteronomio 26 - Los egipcios nos maltrataron, nos oprimieron y nos impusieron una dura esclavitud. Entonces clamamos al Señor, Dios de nuestros padres, y el Señor escuchó nuestra voz.', 'en_EN' => 'Deuteronomy 26 - When the Egyptians treated us harshly and afflicted us, by imposing hard labor on us, we cried to the Lord, the God of our ancestors; the Lord heard our voice.'],
		63 => ['es_ES' => 'Romanos 10 - Porque basta que cada uno declare con su boca que Jesús es el Señor y que crea en su corazón que Dios lo resucitó de entre los muertos, para que pueda salvarse.', 'en_EN' => 'Romans 10 - Because if you confess with your lips that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved.'],
		64 => ['es_ES' => 'Lucas 4 - Entonces el diablo le dijo: “Si eres el Hijo de Dios, dile a esta piedra que se convierta en pan”. Jesús le contestó: “Está escrito: No sólo de pan vive el hombre”.', 'en_EN' => 'Luke 4 - The devil said to him, "If you are the Son of God, command this stone to become a loaf of bread." Jesus answered him, "It is written, \'One does not live by bread alone.\'"'],
		65 => ['es_ES' => 'Deuteronomio 26 - El Señor nos sacó de Egipto con mano poderosa y brazo protector, entre señales y portentos; nos trajo a este país y nos dio esta tierra, que mana leche y miel.', 'en_EN' => 'Deuteronomy 26 - The Lord brought us out of Egypt with a mighty hand and an outstretched arm, with signs and wonders; and he brought us into this place and gave us this land, a land flowing with milk and honey. '],
		66 => ['es_ES' => 'Salmo 91 - Porque has puesto al Señor, que es mi refugio, al Altísimo, por tu habitación. No te sucederá ningún mal, ni plaga se acercará a tu morada.', 'en_EN' => 'Psalm 91 - Because you have made the Lord your refuge, and the Most High your habitation. There shall no evil happen to you, neither shall any plague come near your dwelling.'],
		67 => ['es_ES' => 'Romanos 10 - Por eso dice la Escritura: Ninguno que crea en él quedará defraudado, porque no existe diferencia entre judío y no judío, ya que uno mismo es el Señor de todos, espléndido con todos los que lo invocan.', 'en_EN' => 'Romans 10 - The scripture says, "No one who believes in him will be put to shame." For there is no distinction between Jew and Greek; the same Lord is Lord of all and is generous to all who call on him.'],
		68 => ['es_ES' => 'Lucas 4 - El diablo le dijo: “Todo esto será tuyo, si te arrodillas y me adoras”. Jesús le respondió: “Está escrito: Adorarás al Señor, tu Dios, y a él sólo servirás”.', 'en_EN' => 'Luke 4 - The devil said to him, "If you, then, will worship me, it will all be yours." Jesus answered him, "It is written, \'Worship the Lord your God, and serve only him.\'"'],
		97 => ['es_ES' => 'Lucas 19 - Algunos fariseos que iban entre la gente, le dijeron: "Maestro, reprende a tus discípulos". Él les replicó: "Les aseguro que si ellos se callan, gritarán las piedras". ', 'en_EN' => 'Luke 19 - Some of the Pharisees in the crowd said to him, "Teacher, order your disciples to stop." He answered, "I tell you, if these were silent, the stones would shout out."'],
		98 => ['es_ES' => 'Isaías 50 - Mañana tras mañana, el Señor despierta mi oído, para que escuche yo, como discípulo. El Señor Dios me ha hecho oír sus palabras y yo no he opuesto resistencia ni me he echado atrás.', 'en_EN' => 'Isaiah 50 - Morning by morning he wakens wakens my ear to listen as those who are taught. The Lord God has opened my ear, and I was not rebellious, I did not turn backward.'],
		99 => ['es_ES' => 'Filipenses 2 - Así, hecho uno de ellos, se humilló a sí mismo y por obediencia aceptó incluso la muerte, y una muerte de cruz.', 'en_EN' => 'Philippians 2 - And being found in human form, he humbled himself and became obedient to the point of death even death on a cross.'],
		100 => ['es_ES' => 'Lucas 19 - ¡Bendito el rey que viene en nombre del Señor! ¡Paz en el cielo y gloria en las alturas!', 'en_EN' => 'Luke 19 - Blessed is the king who comes in the name of the Lord!  Peace in heaven, and glory in the highest heaven!'],
		101 => ['es_ES' => 'Isaías 50 - En aquel entonces, dijo Isaías: El Señor me ha dado una lengua experta, para que pueda confortar al abatido con palabras de aliento.', 'en_EN' => 'Isaiah 50 - The Lord God has given me the tongue of a teacher, that I may know how to sustain the weary with a word.'],
		102 => ['es_ES' => 'Filipenses 2 - Al nombre de Jesús, todos doblen la rodilla en el cielo, en la tierra y en los abismos, y todos reconozcan públicamente que Jesucristo es el Señor, para gloria de Dios Padre.', 'en_EN' => 'Philippians 2 - At the name of Jesus every knee should bend, in heaven and on earth and under the earth, and every tongue should confess that Jesus Christ is Lord, to the glory of God the Father.'],
		103 => ['es_ES' => 'Lucas 19 - Conforme iba avanzando, la gente tapizaba el camino con sus mantos, y cuando ya estaba cerca la bajada del monte de los Olivos, la multitud de discípulos, entusiasmados, se pusieron a alabar a Dios a gritos por todos los prodigios que habían visto.', 'en_EN' => 'Luke 19 - As he rode along, people kept spreading their cloaks on the road. As he was now approaching the path down from the Mount of Olives, the whole multitude of the disciples began to praise God joyfully with a loud voice for all the deeds of power that they had seen.'],
		104 => ['es_ES' => 'Isaías 52 - Él soportó el castigo que nos trae la paz. Por sus llagas hemos sido curados.', 'en_EN' => 'Isaiah 52 - Upon him was the punishment that made us whole, and by his bruises we are healed.'],
		105 => ['es_ES' => 'Hebreos 4 - A pesar de que era el Hijo, aprendió a obedecer padeciendo, y llegado a su perfección, se convirtió en la causa de la salvación eterna para todos los que lo obedecen.', 'en_EN' => 'Hebrews 4 - Although he was a Son, he learned obedience through what he suffered; and having been made perfect, he became the source of eternal salvation for all who obey him.'],
		106 => ['es_ES' => 'Isaías 52 - Lo arrancaron de la tierra de los vivos, lo hirieron de muerte por los pecados de mi pueblo,', 'en_EN' => 'Isaiah 52 - For he was cut off from the land of the living, stricken for the transgression of my people.'],
		107 => ['es_ES' => 'Juan 18 - Los soldados sujetaron una esponja empapada en vinagre a una caña de hisopo y se la acercaron a la boca. Jesús probó el vinagre y dijo: “Todo está cumplido”, e inclinando la cabeza, entregó el espíritu.', 'en_EN' => 'John 18 - So they put a sponge full of the wine on a branch of hyssop and held it to his mouth. When Jesus had received the wine, he said, "It is finished." Then he bowed his head and gave up his spirit.'],
		108 => ['es_ES' => 'Hebreos 4 - No tenemos un sumo sacerdote que no sea capaz de compadecerse de nuestros sufrimientos, puesto que él mismo ha pasado por las mismas pruebas que nosotros, excepto el pecado.', 'en_EN' => 'Hebrews 4 - We do not have a high priest who is unable to sympathize with our weaknesses, but we have one who in every respect has been tested as we are, yet without sin.'],
		109 => ['es_ES' => 'Hechos 10 - Él nos mandó predicar al pueblo y dar testimonio de que Dios lo ha constituido juez de vivos y muertos. El testimonio de los profetas es unánime: que cuantos creen en él reciben, por su medio, el perdón de los pecados.', 'en_EN' => 'Acts 10 - He commanded us to preach to the people and to testify that he is the one ordained by God as judge of the living and the dead. All the prophets testify about him that everyone who believes in him receives forgiveness of sins through his name.'],
		110 => ['es_ES' => 'Juan 20 - Entonces entró también el otro discípulo, el que había llegado primero al sepulcro, y vio y creyó, porque hasta entonces no habían entendido las Escrituras, según las cuales Jesús debía resucitar de entre los muertos.', 'en_EN' => 'John 20 - Then the other disciple, who reached the tomb first, also went in, and he saw and believed; for as yet they did not understand the scripture, that he must rise from the dead.'],
		111 => ['es_ES' => 'Apocalipsis 1 - No temas. Yo soy el primero y el último; yo soy el que vive. Estuve muerto y ahora, como ves, estoy vivo por los siglos de los siglos.', 'en_EN' => 'Revelation 1 - To him who loves us and freed us from our sins by his blood, and made us to be a kingdom, priests serving his God and Father, to him be glory and dominion forever and ever.'],
		112 => ['es_ES' => 'Salmo 118 - Tú eres mi Dios, por eso te doy gracias; tú eres mi Dios, por eso te exalto. Den gracias al Señor porque él es bueno; su gran amor perdura para siempre.', 'en_EN' => 'Psalm 118 - You are my God, and I will thank you; you are my God, and I will exalt you. Give thanks to the Lord, for he is good; his mercy endures for ever.'],
		113 => ['es_ES' => 'Hechos 5 - El número de hombres y mujeres que creían en el Señor iba creciendo de día en día, hasta el punto de que tenían que sacar en literas y camillas a los enfermos y ponerlos en las plazas.', 'en_EN' => 'Acts 5 - We gave you strict orders not to teach in this name, yet here you have filled Jerusalem with your teaching and you are determined to bring this man\'s blood on us.'],
		114 => ['es_ES' => 'Juan 20 - Trae acá tu mano, métela en mi costado y no sigas dudando, sino cree”. Tomás le respondió: “¡Señor mío y Dios mío!” Jesús añadió: “Tú crees porque me has visto; dichosos los que creen sin haber visto”.', 'en_EN' => 'John 20 - "Put your finger here and see my hands. Reach out your hand and put it in my side. Do not doubt but believe." Thomas answered him, "My Lord and my God!" Jesus said to him, "Have you believed because you have seen me? Blessed are those who have not seen and yet have come to believe."'],
		115 => ['es_ES' => 'Salmo 118 - El Señor es mi fuerza y mi canción, él es mi salvación. Gritos de júbilo y salvación resuenan en las casas de los justos.', 'en_EN' => 'Psalm 118 - The Lord is my strength and my song, and he has become my salvation.  There is a sound of exultation and victory in the tents of the righteous.'],
		116 => ['es_ES' => 'Hechos 5 - Mucha gente de los alrededores acudía a Jerusalén y llevaba a los enfermos y a los atormentados por espíritus malignos, y todos quedaban curados.', 'en_EN' => 'Acts 5 - The God of our ancestors raised up Jesus, whom you had killed by hanging him on a tree. God exalted him at his right hand as Leader and Savior that he might give repentance to Israel and forgiveness of sins.'],
		117 => ['es_ES' => 'Juan 20 - Se presentó Jesús en medio de ellos y les dijo: “La paz esté con ustedes”. Dicho esto, les mostró las manos y el costado. Cuando los discípulos vieron al Señor, se llenaron de alegría.', 'en_EN' => 'John 20 - Jesus came and stood among them and said, "Peace be with you." After he said this, he showed them his hands and his side. Then the disciples rejoiced when they saw the Lord.'],
	];

	private array $explanation = [
		34 => ['es_ES' => 'Este versículo resalta la disposición a servir al Señor, mostrando un corazón entregado y dispuesto a cumplir su llamada. Responder "Aquí estoy" demuestra fe y valentía para actuar como instrumento de la voluntad divina.', 'en_EN' => 'This verse highlights the willingness to serve the Lord, showing a heart devoted and ready to fulfill His calling. Responding "Here I am" demonstrates faith and courage to act as an instrument of God’s will.'],
		35 => ['es_ES' => 'Dios, a pesar de su grandeza, atiende con amor a los humildes y reconoce la altivez de los orgullosos. Este salmo nos invita a vivir con humildad, confiando en su cuidado, mientras evitamos el orgullo que nos aleja de su gracia.', 'en_EN' => 'God, despite His greatness, lovingly attends to the humble and recognizes the pride of the arrogant. This psalm invites us to live humbly, trusting in His care, while avoiding the pride that distances us from His grace.'],
		36 => ['es_ES' => 'Dios purifica y perdona, renovando el alma de quienes se acercan a Él con sinceridad. Este acto de gracia muestra su poder para transformar vidas, preparándonos para cumplir su propósito con un corazón limpio y reconciliado.', 'en_EN' => 'God purifies and forgives, renewing the soul of those who sincerely approach Him. This act of grace demonstrates His power to transform lives, preparing us to fulfill His purpose with a clean and reconciled heart.'],
		37 => ['es_ES' => 'La obediencia de Simón, confiando en la palabra de Jesús, se convierte en un milagro de abundancia. Este relato enseña a confiar en el Señor incluso cuando las circunstancias parecen desfavorables, pues su poder supera toda expectativa humana.', 'en_EN' => 'Simon’s obedience, trusting in Jesus’ word, results in a miraculous abundance. This story teaches us to trust in the Lord even when circumstances seem unfavorable, for His power surpasses all human expectations.'],
		38 => ['es_ES' => 'Dios es fiel al escuchar nuestras súplicas y fortalecernos en la adversidad. Este salmo nos anima a buscar al Señor con confianza, recordando que su presencia nos llena de valor y nos sostiene en medio de las pruebas.', 'en_EN' => 'God is faithful to hear our prayers and strengthen us in adversity. This psalm encourages us to seek the Lord with confidence, remembering that His presence fills us with courage and sustains us through trials.'],
		39 => ['es_ES' => 'Este pasaje destaca la acción transformadora de la gracia divina, que da sentido y propósito a la vida. Reconocer que todo logro es por su gracia nos impulsa a trabajar con humildad y gratitud, sabiendo que Él nos sostiene.', 'en_EN' => 'This passage emphasizes the transformative action of divine grace, which gives meaning and purpose to life. Recognizing that every achievement comes from His grace inspires us to work with humility and gratitude, knowing He sustains us.'],
		40 => ['es_ES' => 'Jesús transforma la vida de Simón Pedro, llamándolo a una misión mayor. Deja atrás sus temores y acepta el llamado. Este pasaje muestra cómo Dios nos guía hacia propósitos más grandes cuando confiamos y lo seguimos plenamente.', 'en_EN' => 'Jesus transforms Simon Peter’s life, calling him to a greater mission. He leaves his fears behind and accepts the call. This passage shows how God guides us toward greater purposes when we trust and follow Him fully.'],
		41 => ['es_ES' => 'Este pasaje nos recuerda la importancia de poner nuestra confianza en Dios y no depender únicamente de las fuerzas humanas. Solo en Él encontramos estabilidad y vida verdadera, lejos de la aridez espiritual que produce la autosuficiencia.', 'en_EN' => 'This passage reminds us of the importance of placing our trust in God and not relying solely on human strength. Only in Him do we find stability and true life, far from the spiritual dryness that self-sufficiency brings.'],
		42 => ['es_ES' => 'Jesús anima a los perseguidos por su causa a mantenerse firmes y llenos de gozo. Las pruebas en esta vida son temporales, pero la recompensa eterna en el cielo es inmensa y gloriosa para quienes confían en Él.', 'en_EN' => 'Jesus encourages those persecuted for His sake to remain steadfast and joyful. The trials of this life are temporary, but the eternal reward in heaven is immense and glorious for those who trust in Him.'],
		43 => ['es_ES' => 'La resurrección de Cristo confirma nuestra fe y esperanza. Sin ella, no habría vida eterna. Este pasaje nos invita a confiar en la promesa de resurrección, que transforma nuestras vidas con un propósito que trasciende lo terrenal.', 'en_EN' => 'The resurrection of Christ confirms our faith and hope. Without it, there would be no eternal life. This passage invites us to trust in the promise of resurrection, which transforms our lives with a purpose beyond the earthly.'],
		44 => ['es_ES' => 'Quien confía en Dios florece como un árbol junto al agua, siempre lleno de vida, esperanza y fortaleza. Este versículo nos recuerda que solo con nuestras raíces en el Señor podemos resistir las dificultades y vivir en plenitud.', 'en_EN' => 'He who trusts in God flourishes like a tree planted by water, always full of life, hope, and strength. This verse reminds us that only with our roots in the Lord can we endure difficulties and live in fullness.'],
		45 => ['es_ES' => 'Este versículo advierte sobre los peligros de buscar la aprobación del mundo en lugar de la verdad divina. Nos llama a seguir el ejemplo de los verdaderos profetas, guiados por la voluntad de Dios, y no por la vanidad.', 'en_EN' => 'This verse warns about the dangers of seeking the world’s approval instead of divine truth. It calls us to follow the example of true prophets, guided by God’s will rather than vanity and fleeting praise.'],
		46 => ['es_ES' => 'Nuestra fe se fundamenta en la resurrección de Cristo, la garantía de nuestra vida eterna. Este pasaje llena nuestros corazones de alegría y propósito, recordándonos que nuestra esperanza trasciende lo terrenal, guiándonos hacia la gloria celestial.', 'en_EN' => 'Our faith is founded on the resurrection of Christ, the guarantee of eternal life. This passage fills our hearts with joy and purpose, reminding us that our hope transcends the earthly and leads us to heavenly glory.'],
		47 => ['es_ES' => 'Jesús promete esperanza a los pobres, los hambrientos y los que lloran, asegurándoles consuelo y bendición en el Reino de Dios. Este mensaje nos anima a confiar en la justicia divina, que transforma el sufrimiento en gozo eterno.', 'en_EN' => 'Jesus promises hope to the poor, the hungry, and those who weep, assuring them of comfort and blessing in the Kingdom of God. This message encourages us to trust in divine justice, which transforms suffering into eternal joy.'],
		48 => ['es_ES' => 'Adán nos dio la vida terrenal, pero Cristo nos da la vida eterna. Él es el Espíritu que renueva y transforma nuestro ser, guiándonos hacia la plenitud de la comunión con Dios y la esperanza de la resurrección gloriosa.', 'en_EN' => 'Adam gave us earthly life, but Christ gives us eternal life. He is the Spirit who renews and transforms our being, guiding us toward the fullness of communion with God and the hope of glorious resurrection.'],
		49 => ['es_ES' => 'El amor verdadero no se limita a quienes nos aman, sino que se extiende a todos sin condiciones. Jesús nos llama a vivir con generosidad y compasión, reflejando el amor divino que da sin esperar nada a cambio.', 'en_EN' => 'True love is not limited to those who love us but extends unconditionally to all. Jesus calls us to live with generosity and compassion, reflecting the divine love that gives without expecting anything in return.'],
		50 => ['es_ES' => 'José ve la mano de Dios en su historia y elige perdonar. Su actitud nos enseña que incluso en la adversidad, Dios tiene un propósito mayor. Confiar en Él nos permite transformar el dolor en bendición y reconciliación.', 'en_EN' => 'Joseph sees God\'s hand in his story and chooses to forgive. His attitude teaches us that even in adversity, God has a greater purpose. Trusting Him allows us to transform pain into blessing and reconciliation.'],
		51 => ['es_ES' => 'La impaciencia y la ira nos alejan de Dios, mientras que la confianza en Él nos da paz. Este pasaje nos recuerda que el mal no tiene la última palabra, pues quienes esperan en el Señor recibirán su promesa.', 'en_EN' => 'Impatience and anger draw us away from God, while trust in Him gives us peace. This passage reminds us that evil does not have the final word, for those who hope in the Lord will receive His promise.'],
		52 => ['es_ES' => 'El amor de Dios es infinito y nos invita a vivir con la misma misericordia. Al no juzgar ni condenar, sino perdonar, reflejamos su gracia y abrimos nuestro corazón a la paz y la verdadera libertad.', 'en_EN' => 'God\'s love is infinite and calls us to live with the same mercy. By not judging or condemning, but forgiving, we reflect His grace and open our hearts to peace and true freedom.'],
		53 => ['es_ES' => 'Así como heredamos la fragilidad de Adán, en Cristo heredamos la gloria del cielo. Él nos transforma y nos eleva, dándonos la esperanza de una vida renovada, reflejo de su luz y su santidad.', 'en_EN' => 'Just as we inherited Adam\'s frailty, in Christ we inherit the glory of heaven. He transforms and elevates us, giving us the hope of a renewed life, a reflection of His light and holiness.'],
		54 => ['es_ES' => 'Jesús nos llama a un amor sin límites, incluso hacia quienes nos hacen daño. Amar, bendecir y orar por ellos nos libera del rencor y nos acerca a Dios, quien nos enseña que el verdadero poder está en el amor.', 'en_EN' => 'Jesus calls us to boundless love, even toward those who harm us. Loving, blessing, and praying for them frees us from resentment and brings us closer to God, who teaches us that true power lies in love.'],
		55 => ['es_ES' => 'Dios es santo y digno de toda adoración. Postrarnos ante Él es reconocer Su grandeza y entregarle nuestro corazón. Su santidad nos ilumina y nos guía, llamándonos a vivir con fe, humildad y gratitud por Su amor eterno.', 'en_EN' => 'God is holy and worthy of all worship. Bowing before Him means recognizing His greatness and surrendering our hearts. His holiness enlightens and guides us, calling us to live with faith, humility, and gratitude for His eternal love.'],
		56 => ['es_ES' => 'El Padre nos llama a escuchar a Jesús, el camino, la verdad y la vida. Seguir Su palabra nos transforma y nos llena de paz. En Él encontramos la guía segura para nuestra existencia y la promesa de vida eterna.', 'en_EN' => 'The Father calls us to listen to Jesus, the way, the truth, and the life. Following His word transforms us and fills us with peace. In Him, we find the sure guidance for our existence and the promise of eternal life.'],
		57 => ['es_ES' => 'Dios siempre escucha a los que claman con fe. Como lo hizo con Moisés, Aarón y Samuel, también nos responde cuando buscamos Su presencia con sinceridad. Su fidelidad es eterna, y en Él encontramos consuelo y fortaleza en todo momento.', 'en_EN' => 'God always listens to those who call on Him with faith. Just as He did with Moses, Aaron, and Samuel, He also answers us when we sincerely seek His presence. His faithfulness is eternal, and in Him, we find comfort and strength at all times.'],
		58 => ['es_ES' => 'El Espíritu de Dios nos libera del pecado, del miedo y de toda opresión. En Su presencia, somos transformados a Su imagen, reflejando Su gloria. Nos llama a vivir en libertad, amor y verdad, acercándonos cada día más a Él.', 'en_EN' => 'The Spirit of God frees us from sin, fear, and all oppression. In His presence, we are transformed into His image, reflecting His glory. He calls us to live in freedom, love, and truth, drawing us ever closer to Him.'],
		59 => ['es_ES' => 'Jesús nos llama a confiar y tener fe. Su poder es mayor que cualquier adversidad. Aún cuando dudamos, Él nos restaura y nos devuelve la esperanza. Su amor y misericordia son infinitos, sanando nuestras vidas y guiándonos a Su luz.', 'en_EN' => 'Jesus calls us to trust and have faith. His power is greater than any adversity. Even when we doubt, He restores us and gives us hope. His love and mercy are infinite, healing our lives and guiding us to His light.'],
		60 => ['es_ES' => 'Dios es un Padre misericordioso, siempre dispuesto a perdonar. Nos escucha en nuestras dificultades y nos da nuevas oportunidades. Su amor es más grande que nuestras faltas, invitándonos a volver a Él con un corazón sincero y arrepentido.', 'en_EN' => 'God is a merciful Father, always ready to forgive. He listens to us in our difficulties and gives us new opportunities. His love is greater than our faults, inviting us to return to Him with a sincere and repentant heart.'],
		61 => ['es_ES' => 'La gloria de Cristo se manifiesta a quienes están atentos a Su presencia. Aunque el cansancio y las distracciones puedan alejarnos, si permanecemos despiertos en la fe, veremos Su esplendor y experimentaremos la grandeza de Su amor.', 'en_EN' => 'The glory of Christ is revealed to those who are attentive to His presence. Though weariness and distractions may pull us away, if we remain awake in faith, we will see His splendor and experience the greatness of His love.'],
		62 => ['es_ES' => 'Dios nunca abandona a su pueblo en la opresión. Cuando clamamos con fe, Él nos escucha y nos libera. Su amor es más fuerte que cualquier prueba, y su poder nos conduce a la victoria. En Él encontramos esperanza y consuelo en los momentos difíciles.', 'en_EN' => 'God never abandons His people in oppression. When we cry out in faith, He hears us and delivers us. His love is stronger than any trial, and His power leads us to victory. In Him, we find hope and comfort in difficult times.'],
		63 => ['es_ES' => 'La salvación es un regalo divino accesible para todos los que creen. No se trata de esfuerzos humanos, sino de aceptar con fe el amor de Cristo. Confesarlo como Señor nos llena de gracia y nos abre las puertas de la vida eterna.', 'en_EN' => 'Salvation is a divine gift available to all who believe. It is not about human efforts but about accepting Christ’s love in faith. Confessing Him as Lord fills us with grace and opens the doors to eternal life.'],
		64 => ['es_ES' => 'Jesús nos enseña que la vida no se sostiene solo con lo material. Nuestra verdadera necesidad es la Palabra de Dios, que alimenta el alma y fortalece el espíritu. En cada prueba, debemos confiar en el Señor y vivir según su voluntad.', 'en_EN' => 'Jesus teaches us that life is not sustained by material things alone. Our true need is the Word of God, which nourishes the soul and strengthens the spirit. In every trial, we must trust in the Lord and live according to His will.'],
		65 => ['es_ES' => 'Dios es fiel a sus promesas y actúa con poder en favor de su pueblo. Nos libera de la esclavitud del pecado y nos conduce a una vida abundante. Su amor es nuestra fortaleza, y en su protección encontramos seguridad y bendición.', 'en_EN' => 'God is faithful to His promises and acts powerfully on behalf of His people. He frees us from the slavery of sin and leads us to an abundant life. His love is our strength, and in His protection, we find security and blessing.'],
		66 => ['es_ES' => 'En Dios encontramos protección y paz. Él cuida de quienes confían en su amor y los guarda de todo mal. Su presencia es un refugio seguro en tiempos de angustia. Confiar en Él nos llena de fortaleza y esperanza.', 'en_EN' => 'In God, we find protection and peace. He cares for those who trust in His love and guards them from all harm. His presence is a safe refuge in times of distress. Trusting in Him fills us with strength and hope.'],
		67 => ['es_ES' => 'Dios no hace distinción entre sus hijos. Su amor y misericordia alcanzan a todos los que lo buscan con un corazón sincero. La fe en Cristo nos une en una misma esperanza, asegurándonos que su promesa de salvación es firme y eterna.', 'en_EN' => 'God makes no distinction among His children. His love and mercy reach all who seek Him with a sincere heart. Faith in Christ unites us in the same hope, assuring us that His promise of salvation is firm and eternal.'],
		68 => ['es_ES' => 'Jesús nos muestra que solo Dios merece nuestra adoración. Nada en este mundo puede compararse con su grandeza y amor. Mantenernos fieles a Él nos aleja de la tentación y nos conduce a la verdadera felicidad, bajo su guía y bendición.', 'en_EN' => 'Jesus shows us that only God deserves our worship. Nothing in this world compares to His greatness and love. Remaining faithful to Him keeps us away from temptation and leads us to true happiness under His guidance and blessing.'],
		97 => ['es_ES' => 'El mensaje de Dios es tan poderoso que no puede ser silenciado. Si los corazones humanos callan, la creación entera proclamará su gloria. Nada puede apagar la alabanza auténtica. Reconocer a Cristo es participar de la verdad que clama desde lo más profundo de la existencia.', 'en_EN' => 'God’s message is so powerful it cannot be silenced. If human hearts fall silent, creation itself will proclaim His glory. Nothing can suppress true praise. Acknowledging Christ means joining in the truth that cries out from the very depths of existence.'],
		98 => ['es_ES' => 'Dios nos llama cada día a una escucha activa y humilde. Nos forma como discípulos atentos, dispuestos a recibir su palabra con docilidad. Escucharle nos transforma, nos da dirección, y nos capacita para vivir con fidelidad, respondiendo con amor al llamado que Él nos dirige.', 'en_EN' => 'God calls us each day to active and humble listening. He shapes us into attentive disciples, ready to receive His word with openness. Listening to Him transforms us, gives us direction, and enables us to respond with love to the calling He places in our hearts.'],
		99 => ['es_ES' => 'Jesús nos enseña que la verdadera grandeza está en la humildad y el servicio. Su entrega hasta la cruz es el acto supremo de amor y obediencia. En Él descubrimos que el sacrificio, asumido por amor, se convierte en victoria y en camino hacia la vida eterna.', 'en_EN' => 'Jesus teaches us that true greatness lies in humility and service. His surrender on the cross is the supreme act of love and obedience. In Him, we discover that sacrifice embraced in love becomes victory and the pathway to eternal life.'],
		100 => ['es_ES' => 'La entrada de Jesús en Jerusalén es un canto de esperanza. Él viene como Rey de paz, trayendo salvación y alegría. Su presencia transforma corazones, sana heridas y nos invita a recibirlo con júbilo. Bendito sea el que trae luz y vida a nuestro mundo.', 'en_EN' => 'Jesus’ entry into Jerusalem is a song of hope. He comes as the King of peace, bringing salvation and joy. His presence transforms hearts, heals wounds, and invites us to welcome Him with joy. Blessed is He who brings light and life to our world.'],
		101 => ['es_ES' => 'Dios capacita a sus siervos para consolar y alentar. Sus palabras en nosotros se convierten en bálsamo para los que sufren. Cuando escuchamos su voz, también aprendemos a hablar con ternura, a levantar al caído y a ser instrumentos de esperanza para los demás.', 'en_EN' => 'God equips His servants to bring comfort and encouragement. His words in us become balm for those who suffer. When we listen to His voice, we also learn to speak with tenderness, lift up the fallen, and be instruments of hope to others.'],
		102 => ['es_ES' => 'Jesucristo es exaltado por su amor y obediencia. Su nombre es fuente de poder, consuelo y redención. Ante Él se rinde toda la creación, reconociendo su señorío. Honrar a Jesús nos une a la gloria del Padre y nos llena de paz y reverencia.', 'en_EN' => 'Jesus Christ is exalted for His love and obedience. His name is a source of power, comfort, and redemption. All creation bows before Him, recognizing His lordship. Honoring Jesus unites us to the Father’s glory and fills us with peace and reverence.'],
		103 => ['es_ES' => 'Cuando contemplamos la obra de Dios en nuestras vidas, no podemos guardar silencio. Su presencia provoca alegría y alabanza. Celebrar sus maravillas fortalece nuestra fe y nos une como comunidad. Que nunca nos falte gratitud para proclamar con gozo todo lo que Él ha hecho.', 'en_EN' => 'When we witness God’s work in our lives, we cannot stay silent. His presence stirs joy and praise. Celebrating His wonders strengthens our faith and unites us as a community. May we never lack the gratitude to proclaim joyfully all that He has done.'],
		104 => ['es_ES' => 'Jesús asumió nuestro dolor y abrió el camino hacia la paz verdadera. Sus heridas son fuente de sanación para nuestras almas. En su entrega encontramos el amor redentor que transforma la culpa en gracia y la tristeza en esperanza. Por Él, hoy vivimos reconciliados con Dios.', 'en_EN' => 'Jesus bore our pain and opened the way to true peace. His wounds are a source of healing for our souls. In His sacrifice, we find redemptive love that turns guilt into grace and sorrow into hope. Through Him, we now live reconciled with God.'],
		105 => ['es_ES' => 'El sufrimiento de Cristo no fue en vano: fue el camino hacia la perfección que nos trajo la salvación eterna. Su obediencia nos enseña a confiar en Dios, incluso en el dolor. En Cristo, todo sacrificio tiene un propósito eterno, y la obediencia es una fuente de vida.', 'en_EN' => 'Christ’s suffering was not in vain: it was the path to perfection that brought us eternal salvation. His obedience teaches us to trust God, even in pain. In Christ, every sacrifice has an eternal purpose, and obedience becomes a fountain of life and divine blessing.'],
		106 => ['es_ES' => 'Jesús aceptó la cruz como expresión suprema de amor. Cargó con nuestras faltas para que nosotros fuéramos liberados del peso del pecado. Su muerte nos da nueva vida. En su sacrificio reconocemos el mayor acto de misericordia divina y la esperanza de la redención universal.', 'en_EN' => 'Jesus embraced the cross as the supreme expression of love. He carried our sins so we could be freed from their burden. His death gives us new life. In His sacrifice, we recognize the greatest act of divine mercy and the universal hope of redemption.'],
		107 => ['es_ES' => 'Con estas palabras, Jesús declara la victoria del amor sobre el pecado y la muerte. Su misión se ha cumplido: la redención ha sido conquistada. Su entrega total nos asegura que nada nos separará del amor de Dios. Su Espíritu vive en nosotros y nos llena de vida nueva.', 'en_EN' => 'With these words, Jesus proclaims love’s victory over sin and death. His mission is complete: redemption has been accomplished. His total surrender assures us that nothing can separate us from God\'s love. His Spirit lives within us and fills us with renewed life and hope.'],
		108 => ['es_ES' => 'Jesús, nuestro sumo sacerdote, comprende cada una de nuestras luchas porque Él mismo las vivió. No juzga desde la distancia, sino que camina a nuestro lado con compasión y ternura. Su cercanía nos fortalece, nos anima y nos impulsa a vivir con fe y confianza renovadas.', 'en_EN' => 'Jesus, our high priest, understands every one of our struggles because He lived them Himself. He does not judge from afar but walks with us with compassion and gentleness. His closeness strengthens us, encourages us, and leads us to live with renewed faith and trust.'],
		109 => ['es_ES' => 'Cristo es juez y redentor. En Él se cumplen las promesas proféticas de salvación. Su mensaje es universal: ofrece perdón, vida y esperanza a todos los que creen. Nuestra misión es anunciar esta buena noticia con alegría, sabiendo que su gracia transforma corazones y renueva el mundo.', 'en_EN' => 'Christ is both judge and redeemer. In Him, the prophetic promises of salvation are fulfilled. His message is universal: He offers forgiveness, life, and hope to all who believe. Our mission is to joyfully proclaim this good news, knowing His grace transforms hearts and renews the world.'],
		110 => ['es_ES' => 'La fe nace del encuentro con el Resucitado. Al ver el sepulcro vacío, el discípulo comprende que la muerte ha sido vencida. Jesús vive, y su victoria es también la nuestra. Esta fe nos impulsa a vivir con gozo, sabiendo que la luz siempre triunfa sobre la oscuridad.', 'en_EN' => 'Faith is born from the encounter with the Risen One. Upon seeing the empty tomb, the disciple understands that death has been conquered. Jesus lives, and His victory is ours too. This faith moves us to live joyfully, knowing that light always triumphs over darkness.'],
		111 => ['es_ES' => 'Cristo, vencedor de la muerte, nos asegura que Él vive eternamente. En sus palabras hay consuelo y poder: no debemos temer. Él es el principio y el fin, nuestra esperanza firme en todo tiempo. Su presencia viva nos sostiene y nos invita a caminar confiados, guiados por su luz.', 'en_EN' => 'Christ loves us deeply and has freed us from sin with His blood. He has made us part of His kingdom, priests in service to God. His glory and power are eternal. Living in His love is living in freedom, dignity, and purpose. To Him be praise forever!'],
		112 => ['es_ES' => 'Nuestro corazón se llena de gratitud al reconocer a Dios como nuestro Señor. Su amor no tiene fin, su bondad es eterna. Alabarlo es reconocer su fidelidad en cada paso. En medio de las pruebas o la alegría, Él es digno de exaltación por su amor que nunca falla.', 'en_EN' => 'Our hearts are filled with gratitude as we recognize God as our Lord. His love never ends, His goodness is eternal. To praise Him is to acknowledge His faithfulness in every step. In the midst of trials or joy, He is worthy of exaltation for His love that never fails.'],
		113 => ['es_ES' => 'El poder del Señor se manifestaba con fuerza en la comunidad de creyentes. La fe crecía, y con ella, la esperanza de sanación y vida nueva. La presencia de Dios transformaba corazones y cuerpos, mostrando que donde reina Cristo, abundan los milagros, la compasión y el amor verdadero.', 'en_EN' => 'Despite opposition, the apostles boldly proclaimed the name of Jesus. Their firm faith filled Jerusalem with the message of life and salvation. Even today, nothing can stop the truth of the Gospel when it burns in willing hearts. Christ transforms, liberates, and gives life its eternal meaning.'],
		114 => ['es_ES' => 'Tomás reconoció a Jesús resucitado, pero Jesús nos invita a creer incluso sin ver, bendiciendo a quienes confían en su poder invisible. Esta bienaventuranza nos fortalece: creer es abrir el alma al amor eterno de Dios y encontrar en Él sentido, paz y vida verdadera.', 'en_EN' => 'Thomas recognized the risen Jesus, but Jesus invites us to believe even without seeing, blessing those who trust in His unseen power. This beatitude strengthens us: to believe is to open the soul to God’s eternal love and to find in Him meaning, peace, and true life.'],
		115 => ['es_ES' => 'Dios es nuestra fortaleza en el dolor y nuestro canto en la alegría. Él nos salva y nos renueva. Su presencia llena nuestras casas de gozo y esperanza. Allí donde se confía en el Señor, brotan alabanzas, y su victoria resuena como música de fe entre los justos.', 'en_EN' => 'God is our strength in sorrow and our song in joy. He saves and renews us. His presence fills our homes with hope and gladness. Where there is trust in the Lord, praise flows, and His victory resounds like music of faith among the righteous.'],
		116 => ['es_ES' => 'La fe del pueblo era tan fuerte que traían a los enfermos confiando en el poder sanador del Señor. La misericordia de Dios alcanzaba a todos. Su Espíritu obraba con poder, mostrando que donde hay fe viva y comunidad unida, el amor divino sana, libera y transforma vidas.', 'en_EN' => 'The people’s faith was so strong they brought out the sick, trusting in the Lord’s healing power. God\'s mercy reached everyone. His Spirit worked with power, showing that where there is living faith and a united community, divine love heals, frees, and transforms lives.'],
		117 => ['es_ES' => 'Jesús resucitado trae su paz a los corazones turbados. Al mostrarse a sus discípulos, enciende en ellos la alegría de la vida nueva. Su paz es regalo divino que vence el miedo. Su presencia transforma la tristeza en júbilo, y su amor nos envuelve con gozo inquebrantable.', 'en_EN' => 'The risen Jesus brings peace to troubled hearts. When He appeared to His disciples, He ignited in them the joy of new life. His peace is a divine gift that overcomes fear. His presence transforms sorrow into joy, and His love surrounds us with unshakable gladness.'],
	];


	/**
	 * Run the database seeds.
	 */
	public function run(): void
	{
		DB::table($this->galleryTable)->updateOrInsert([
			'product_type_id' => 23,
		]);

		$contentId = DB::table($this->galleryTable)
			->where('product_type_id', 23)
			->value('id');


		foreach ($this->verse as $order => $content) {
			$data = [
				'gallery_id' => $contentId,
				'order' => $order,
				'layout_reference' => 'verse',
			];

			foreach ($content as $locale => $text) {
				$data[$locale] = $text;
			}

			DB::table($this->textsTable)->insert($data);
		}

		foreach ($this->explanation as $order => $content) {
			$data = [
				'gallery_id' => $contentId,
				'order' => $order,
				'layout_reference' => 'explanation',
			];

			foreach ($content as $locale => $text) {
				$data[$locale] = $text;
			}

			DB::table($this->textsTable)->insert($data);
		}
	}
}
