<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

final class Fancelet_LOB1Seeder extends Seeder
{
	protected $galleryTable = 'fancelet_content_gallery';
	protected $textsTable = 'fancelet_content_texts';
	protected $imagesTable = 'fancelet_content_images';

	private array $images = [
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/001.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/002.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/003.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/004.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/005.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/006.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/007.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/008.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/009.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/010.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/011.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/012.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/013.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/014.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/015.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/016.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/017.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/018.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/019.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/020.png',
		'https://fancelets.s3.eu-west-3.amazonaws.com/LOB1/images/021.png',
	];

	private array $texts = [
		'en_EN' => [
			'Love is finding in the other a refuge, a safe place to share your fears, dreams, and hopes.',
			'Love is not just a feeling, it is a daily choice to care for each other and grow together in harmony.',
			'True love is patience, understanding, and the will to overcome any obstacle together.',
			'In love, simple moments are the most valuable: a smile, a glance, a hug that says it all.',
			'Loving is not finding someone perfect, but someone with whom to build a life full of acceptance and mutual respect.',
			'Love is sharing comfortable silences, those where no words are needed to feel the deep connection between both.',
			"Loving is being there for each other in difficult moments, being the other's strength when life becomes uncertain.",
			'True love is not measured in words, but in actions that demonstrate a deep and sincere commitment.',
			'In romantic love, differences enrich, as together you learn to see the world with a broader perspective.',
			'Loving is being vulnerable, opening your heart without fear of being hurt, fully trusting the other person.',
			'Love is not just an emotion but a constant commitment of support, respect, and the will to grow together.',
			'In love, small gestures speak louder than grand promises: a hug, a sincere gesture, a glance.',
			'Loving is finding peace in the arms of someone who understands you without the need for explanations or words.',
			'Love is not about being perfect, but about accepting each other and growing together, overcoming imperfections together.',
			'True love is not only seen in happy moments but in how you support each other in times of difficulty.',
			'In love, trust is key. When you trust fully, everything else in the relationship flows easily.',
			"Loving is knowing that, even in silence, you can find comfort and strength in the other's presence.",
			'Romantic love is an adventure, a journey of constant discovery about the other and oneself.',
			'Loving is being willing to make sacrifices, but also to receive with gratitude everything the other offers.',
			"True love is giving without expecting anything in return, because the most important thing is the other person's happiness.",
			'Romantic love is like a dance, where two people move to the same rhythm, balancing each other.',
			'Loving is feeling that, being with that person, everything makes more sense, as if everything falls into place.',
			'In love, differences do not divide; they embrace them, turning them into something beautiful that enriches the relationship.',
			'Love is the foundation on which a life full of shared moments and unforgettable memories is built.',
			'Love is not perfect, but in its imperfection, its true beauty lies, the kind that helps you grow.',
			'Loving is learning to communicate even in silence, understanding that sometimes words are not necessary.',
			'Love is the trust that is built over time, strengthening through every sincere gesture and action.',
			"Loving is being willing to invest time and effort, building a strong relationship that withstands life's adversities.",
			'In love, every day is an opportunity to choose to be better, to care for and deeply value the other.',
			'Romantic love is a space where both can be authentic, without fear of judgment, knowing that they are accepted.',
			'Loving is creating memories together, those simple moments that become the most valuable over time.',
			'True love is supporting the other person in their dreams, encouraging them to grow and be their best self.',
			"Love is patience in difficult days, support when things aren't going well, without hesitation.",
			'Loving is sharing your thoughts, fears, and joys, knowing that the other listens and understands you.',
			'Love is like a garden that grows with care, patience, and dedication, blooming in moments of shared tenderness.',
			'Romantic love is about being a team, working together to overcome everything life throws at you.',
			'In love, emotions flow freely, without fear of being vulnerable or showing the deepest parts of oneself.',
			'Loving is not fearing the future because you know that, with that person, any challenge will be easier to face.',
			'Romantic love feeds on trust and respect, creating a solid foundation that withstands any storm that comes.',
			'Loving is looking at the other person and seeing not only what they are, but also what they can become.',
			'Love is a shared journey, where the final destination matters less than the experiences lived together.',
			'In love, every gesture of affection, no matter how small, has the power to strengthen the bond between two people.',
			'Loving is offering the best of yourself, knowing that in a true relationship, both give equally sincerely.',
			'Love is not about finding someone who completes you, but someone with whom you can be complete.',
			'Romantic love is about growing together, learning from every mistake, celebrating every success, and always supporting each other.',
			'Loving is accepting the other person just as they are, with all their flaws, strengths, imperfections, and virtues.',
			'Romantic love is not measured by the days but by the moments shared and the quality of the connection.',
			'Loving is finding someone to share not just the good times but also the challenges in life.',
			'Love is being together, not just in moments of happiness, but also in times of sadness and difficulty.',
			'In love, complicity is everything: knowing that the other understands you without saying a word.',
			'Loving is accepting vulnerability, trusting the other, and knowing that, no matter what, you will always be together.',
			'Love is the magic that happens when two people understand each other without the need to explain everything in detail.',
			"Loving is caring for the other even on days when they don't feel their best, showing support and understanding.",
			"True love is the one that doesn't seek to change the other but celebrates them just as they are, with all their nuances.",
			"In romantic love, every day has its own beauty, even if it's not perfect, because what's important is the company.",
			'Loving is recognizing in the other a refuge where you can be yourself, without fear of being judged.',
			'Love is knowing that, no matter the differences, there is always room for understanding and mutual empathy.',
			'Loving is sharing your life with someone who chooses you every day, regardless of circumstances or obstacles.',
			'In love, respect and trust are the fundamental pillars that support the relationship, allowing it to grow and thrive.',
			'Loving is seeing the beauty of life through the eyes of the person you love, sharing every moment.',
			'Love is the ability to understand, forgive, and accept the other, even when circumstances are hard to face.',
			'Loving is creating a bond so strong that neither time nor difficulties can break it, always persevering together.',
			'Love is giving without expecting, because the most important thing is to see the other happy and whole by your side.',
			"Loving is knowing that no matter how complicated the day is, you can always count on the other's unconditional support.",
			'Romantic love is that feeling of security you find in the person who matters most to you, no matter anything else.',
			"In love, promises are fulfilled with actions, not just words; it's the gestures that truly matter.",
			'Loving is being able to be vulnerable, showing your heart, and knowing it will be protected by the person you love.',
			'Love is finding in the other someone who makes you feel complete, who makes you better every day.',
			"In love, it's not about losing yourself in the other, but growing together, respecting each other's individuality.",
			"Loving is enjoying each other's company, the little moments, the simplicity of being together without needing more.",
			"Romantic love is that feeling of knowing there's always someone waiting for you, willing to support you in everything.",
			'Loving is sharing life with someone who makes you feel special, who values every moment and detail.',
			'In love, every word feels like a hug, every gesture like a testament of sincere and unconditional affection.',
			'True love is feeling that, no matter what happens, the other will always be there, strong and present.',
			'Loving is not only wanting someone, but also respecting their dreams, their goals, and their deepest desires.',
			'Love is the feeling of peace that comes when you find someone who understands you without needing words.',
			'Romantic love is when two people become one, sharing everything, without losing their individuality or essence.',
			'Loving is accepting the ups and downs of life, knowing that together, you can overcome any adversity with love and understanding.',
			'Love is the constant giving, not only in words but in actions that show how much that person matters to you.',
			'In love, every conflict is an opportunity to grow together, learn more about the other, and strengthen the relationship.',
			'Loving is finding peace in the other’s presence, knowing that, with them, everything else can wait.',
			'Love is the ability to look at the other and see in their eyes a reflection of your own dreams.',
			'Loving is wanting to share all your days, from the happiest to the most difficult, with that special person.',
			'Romantic love is trusting fully, knowing that the other will always be there to support and lift you up when you fall.',
			"In love, time doesn't matter as much; what counts is the quality of the moments shared together.",
			"Loving is feeling that, when you look into someone's eyes, you can see your future reflected in their pupils.",
			'Love is when two people decide to be strong together, because they know that one’s strength strengthens the other.',
			'Loving is a journey full of challenges, but also moments of joy, love, and the constant building of something beautiful.',
			'Love is knowing that, even as the world changes, the connection with that person will always be an anchor in your life.',
			'Loving is building a life story together, full of laughter, challenges, hugs, and memories that last through time.',
			'Love is the freedom to be yourself, without fear of judgment, because the other always accepts you just as you are.',
			'Loving is supporting the other in their dreams and challenges, being their partner and greatest support at all times.',
			'Romantic love is finding in the other person a reason to smile, even on the darkest days.',
			'Loving is sharing dreams, fears, and hopes with someone who listens and supports you every step of the way.',
			'Love is knowing that, even if there are no answers, the other’s presence is enough to find comfort.',
			"In love, it doesn't matter how many times you fall, what matters is that there will always be someone there to lift you up.",
			'Loving is making the other person’s life a little easier, happier, and more meaningful with every action.',
			'Love is the peace of knowing that, no matter what happens, you will always have someone to share everything with.',
			'True love is seeing the other person not just with your eyes, but also with your heart.',
			'Loving is giving yourself fully, but also receiving with gratitude everything the other has to offer.',
			'Love is knowing that, despite the difficulties, you can always count on the unconditional support of that special person.',
			'Loving is giving yourself without fear, trusting the other, and feeling that together you are stronger than any adversity.',
			'Love is a constant adventure, where the destination is uncertain, but the company of the other always brings peace.',
			'In love, the most important thing is not what we receive, but what we give to the person we love.',
			'Loving is making the other feel unique, special, and appreciated, showing them how valuable they are in your life.',
			'True love is fed by mutual trust, patience, and understanding, creating an unbreakable bond.',
			'Loving is seeing in the other a reflection of your own dreams, fears, and desires, and embracing them together.',
			'Love is not only about emotions, but daily actions that show care and dedication.',
			'Loving is feeling at peace with yourself when you are with that person, knowing that there is no safer place.',
			'Romantic love is the magic that happens when two people choose each other, day after day, with their hearts.',
			'Loving is not only being together in good times, but also being willing to support each other in difficult moments.',
			'Love is being able to look at the other and, in their gaze, see your own dreams and hopes reflected.',
			'In love, the most valuable thing is silent understanding, the ability to understand without the need for words.',
			'Love is the commitment to continue growing together, learning from mistakes, and celebrating achievements as a couple.',
			'Loving is giving without expecting, it’s the satisfaction of seeing the other happy with your simple presence.',
			'True love is trusting without doubt, feeling that nothing can separate you because you are deeply connected.',
			'In love, words are important, but gestures, actions, and mutual dedication are what truly matter.',
			'Loving is learning to share life, dreams, and fears, knowing that both support each other without reservations.',
			'Romantic love is a continuous journey of discovery, where every day you are surprised by getting to know your partner more deeply.',
			'Loving is feeling that, with that person by your side, everything seems easier, simpler, and filled with light.',
			'Love is understanding that true commitment is not measured by words, but by constant actions.',
			'In love, every small gesture counts: a kiss, a hug, a caress—each one leaves a mark on the soul.',
			'Loving is being willing to build a future together, knowing that the happiness of the other is part of your own.',
			'Love is the force that drives you to be better, overcome your fears, and achieve your dreams.',
			'Loving is sharing your most intimate moments, your deepest thoughts, and finding a compassionate response in the other.',
			'True love is when two people choose each other, not out of need, but because they truly love and value each other.',
			'Loving is learning to accept each other, with all the differences and peculiarities, knowing that what matters is the bond.',
			'Love is a refuge in times of storm, where you can find comfort, strength, and hope to keep going.',
			'In love, sincerity is fundamental. Being transparent and authentic is the foundation for building a solid relationship.',
			'Loving is giving everything you have, without holding back, knowing that the other person will do the same for you.',
			'Love is a language without barriers, a constant dialogue of glances, gestures, and small details that strengthen the relationship.',
			'Loving is knowing that, no matter the time or circumstances, you will always have a special place in the other’s heart.',
			'In romantic love, honesty is essential; sharing what we feel and think brings us closer and strengthens the relationship.',
			'Loving is feeling that your heart beats faster when you are near that person, as if the world stops.',
			'Love doesn’t seek to change the other, but to accept them and walk alongside them on their path of personal and joint growth.',
			'Loving is learning to forgive, letting go of grudges, and moving forward, always with the intention of strengthening love.',
			'Love is when a look can say everything that words cannot express, everything you feel.',
			'In love, every day is an opportunity to make the other feel special, to show them how valuable they are.',
			'Loving is being the refuge of the other, the person they trust fully, without fears or reservations.',
			'Romantic love is a silent pact of respect and loyalty, where two people choose each other without conditions or doubts.',
			'Loving is knowing that, despite the difficulties, you will always be by the side of the person you love.',
			'Love is discovering that you don’t need to be perfect, because the person who loves you accepts you just as you are.',
			'In love, patience is key. Knowing how to wait, give space, and time for the relationship to grow and strengthen.',
			'Loving is walking by the other’s side, shoulder to shoulder, facing together whatever life has prepared.',
			'Romantic love is the art of making the other feel unique and special, through sincere gestures and words.',
			'Loving is witnessing the evolution of the other person, seeing how they transform, and growing together in the process.',
			'In love, trust is fundamental. Knowing that the other person is there, ready to support you, no matter what happens.',
			'Loving is sharing your fears and joys, with the certainty that the other is always ready to listen.',
			'Love is that spark that lights up everyday life, turning the mundane into something beautiful when shared with someone special.',
			'Loving is not fearing vulnerability, because you know the other person cares for you and respects you just as you are.',
			'Love is an unwritten promise, but it is lived out in every action and decision made together.',
			'In love, complicity is fundamental. Being able to understand each other with just a glance, without words, strengthens the relationship.',
			'Loving is believing in the other, in their potential, in their dreams, and supporting them so they can achieve all they desire.',
			'True love is not measured by what is given or received, but by what is built together.',
			'Loving is learning to enjoy the small moments, because it is those that truly strengthen the relationship in the long run.',
			'Love is the commitment to be together through everything, not just when things are going well, but also in difficult moments.',
			'In romantic love, the most important thing is the emotional connection, one that doesn’t need words, just the presence of the other.',
			'Loving is learning to listen, not only with the ears, but also with the heart, understanding what is not said.',
			'Love is being life partners, sharing both the happy moments and the challenges, always with mutual support.',
			'Loving is building a life together, knowing that, despite the difficulties, there is always something that deeply unites you.',
			'In love, trust and mutual respect are the foundations that sustain a solid and lasting relationship.',
			'Loving is the freedom to be yourself, without fear of judgment, because the other accepts you with everything you are.',
			'Romantic love is the refuge where you find yourself, while giving yourself completely to the other.',
			'Loving is building a bond that withstands adversities, grows stronger with each challenge, and constantly renews itself.',
			'In love, every sacrifice is worth it, because in the end, what matters is the happiness of the person you love.',
			'Loving is a continuous commitment of care, respect, and dedication, where every day effort is made to improve the relationship.',
			'Love is when you find in someone not only a partner, but a true friend with whom to share everything.',
			'Loving is choosing to walk together, regardless of obstacles, always trusting in the other’s unconditional support.',
			'In love, open and sincere communication is essential, as it allows misunderstandings to be resolved and strengthens emotional connection.',
			'Loving is an act of generosity, giving your best to make the other person happy.',
			'Romantic love is the force that drives two people to overcome their fears and achieve great things together.',
			'Loving is knowing that, even though the future is uncertain, the present shared with that person is all you need.',
			'In love, the moments shared become memories we treasure forever, building together a life story.',
			'Loving is taking care of the other in every way, body, mind, and soul, and being their refuge when needed.',
			'Love is the courage to be vulnerable, to show who you truly are, and knowing the other accepts you.',
			'Loving is making the other a priority in your life, because their happiness is as important as your own.',
			'Love is learning to grow together, to evolve as a couple, while staying firm in the values you share.',
			'Loving is knowing that no matter what happens, you will always have a special place in the other’s heart.',
			'In love, every gesture counts, every word, every action, all are ways to show how much you care.',
			'Loving is making the other’s life easier, happier, and more meaningful with every action and word.',
			'Romantic love is the act of sharing the most intimate and personal moments, creating a deep and unique connection.',
			'Loving is being able to see in the other’s eyes a life full of dreams, challenges, and hopes.',
			'In love, every day is an opportunity to make the person you love happy, to show them your affection.',
			'Loving is being the refuge and strength of the other, the person they can always trust, no matter what happens.',
			'Love is a constant dance between giving and receiving, between being strong and vulnerable, always growing together as a couple.',
			'Loving is understanding that the other person has their own fears and dreams, and being willing to accompany them on their journey.',
			'Love is the certainty that, no matter the circumstances, you will never face life alone.',
			'In love, loyalty and honesty are the fundamental pillars on which a lasting relationship is built.',
			'Loving is living each day with the desire to make the other’s life easier, happier, and more fulfilling.',
			'Love is when two people meet at just the right moment, creating a unique bond that cannot be broken.',
			'In love, every conflict is an opportunity to grow, learn, and strengthen the bond between two people who care for each other.',
			'Loving is knowing that, no matter what happens, you will always have a home in the arms of that special person.',
			'Love is a promise of constant support, being there for each other no matter the circumstances you face together.',
			'Loving is a journey that is enjoyed in the present, with your eyes set on the future you will build together.',
			'In love, every sacrifice made for the well-being of the other becomes a sign of how deep the affection is.',
			'Loving is learning to find beauty in the other’s imperfections, knowing that it is what makes them unique and special.',
			'Love is sharing emotions, challenges, and achievements, because together you are stronger than apart.',
			'Loving is knowing that the other will always be there, ready to offer their love, support, and understanding at any time.',
			'Love is the peace of knowing that, with that person, the world seems like a kinder, more hopeful place.',
			'In love, every detail counts—every word, every gesture—because they all contribute to strengthening the bond between two people who love each other.',
			'Loving is the certainty that, despite differences, there is always something that unites you: a deep love and respect.',
			'Love is understanding the other person in their entirety, accepting their flaws, strengths, dreams, and fears, without wanting to change anything about them.',
			'Loving is learning to care for the other, to worry about their well-being, and to offer unconditional support when they need it.',
			'Love is a relationship of mutual growth, where both push each other to be better and achieve their dreams together.',
			'In love, it’s not about being perfect, but about being authentic, sincere, and true with each other.',
			'Loving is sharing life with someone who understands you, respects you, and values you for who you are.',
			'Love is knowing that, although everything changes, there will always be something constant: the commitment and affection shared between both.',
			'Loving is feeling at home, not just in the physical space, but in the arms and heart of that person.',
			'Love is the desire to see the other grow, be happy, and fulfill their dreams, always supporting them without reservation.',
			'In love, trust is key to building a solid and lasting relationship, a foundation that can withstand any trial.',
			'Loving is sharing the small everyday moments, because in them are the seeds of a deep and lasting relationship.',
			'Love is when two people choose each other mutually, without promises of perfection, but with the will to be better together.',
			'In love, empathy and understanding are essential, because they allow us to see the world through the other’s eyes.',
			'Loving is walking through life together, step by step, facing every challenge that destiny brings.',
			'Love is not just a feeling, but a constant decision to make the other person feel special and loved.',
			'Loving is sharing your life with someone who supports you, understands you, and gives you space to be who you are.',
			'Love is the force that drives us to care for someone beyond ourselves, putting them before anything.',
			'In love, dedication and mutual commitment are what make the relationship stronger and grow over time.',
			'Loving is having the certainty that, no matter what happens, you will always overcome any obstacle together.',
			'Love is when two people support each other to achieve their dreams, without fear of the difficulties that may arise.',
			'Loving is choosing each other every day, not out of obligation, but because in the other you find everything you need.',
			'In love, acceptance is fundamental. Accepting the other as they are, without trying to change them, strengthens the relationship.',
			'Love is sharing your fears, dreams, and hopes, knowing that, with the support of the other, everything will be possible.',
			'Loving is a deep connection that goes beyond the physical; it’s sharing souls and hearts, without fear or reservations.',
			'Love is when a smile from that person makes you feel that everything in the world is right.',
			'In love, patience is important. Learning to wait and trust the process is essential for a lasting relationship.',
			'Loving is being able to put the other’s well-being first, knowing that their happiness will also be yours.',
			'Love is discovering new horizons together, building a shared future, and enjoying every step taken as a couple.',
			'In love, the little things matter more than they seem, because it’s the details that make the difference.',
			'Loving is walking in sync, like two pieces that fit perfectly in the puzzle of life.',
			'Love is always being willing to make sacrifices for the other, because the happiness of the partner is a priority.',
			'In love, vulnerability becomes a strength, because it allows the other to see your true self.',
			'Loving is learning that love is not always perfect, but the beauty lies in the ability to overcome everything.',
			'Love is that safe haven where you can be yourself, without masks or fears, knowing you are accepted.',
			'In love, mutual respect and understanding are the pillars that keep the relationship strong and healthy.',
			'Loving is feeling that, with that person by your side, the future doesn’t seem so uncertain or feared.',
			'Love is the promise to walk together through all the seasons of life, enjoying both the flowers and the storms.',
			'Loving is when, even on gray days, that person can bring a smile to your face just by looking at you.',
			'Love is when you find someone with whom to share your soul, and that connection becomes something eternal.',
			'In love, the most beautiful thing is the complicity, the mutual understanding without words, the peace found in gestures.',
			'Loving is a journey where each day is a new adventure, and every moment together becomes an unforgettable memory.',
			'Love is the impulse that drives you to care for someone, to do everything possible to make them happy.',
			'In love, there is no fear, because when you love, you know that there will always be a hug waiting to comfort you.',
			'Loving is being aware that together you can build a love that is much stronger than any difficulty.',
			'Love is when, even in the routine, you find magical moments just by being with the other person.',
			'In love, every day is an opportunity to strengthen the bond, to learn more about the other and about yourself.',
			'Loving is sharing your achievements and failures, knowing the other will be there to celebrate or console you.',
			'Love is when you feel grateful to have that person by your side, sharing every moment of your life.',
			'In love, everything is possible, because with the strength of two united hearts, great things can be achieved.',
			'Loving is being the unconditional support for the other, helping each other grow and evolve as individuals and as a couple.',
			'Love is living a constant present, where the only thing that matters is being together, without thinking too much about the future.',
			'In love, the mutual effort to build a future together is what makes the relationship solid.',
			'Loving is recognizing that, even though the world is uncertain, love is a constant in both of your lives.',
			'Love is trusting the other completely, knowing that you will always have a special place in each other’s hearts.',
			'In love, respect is essential, because without it, any relationship can lose its stability and growth.',
			'Loving is being willing to commit, to give in, to negotiate, but always seeking what is best for both.',
			'Love is a reflection of two souls that meet, understand, and choose each other with both heart and mind.',
			'In love, beauty is not only in the physical, but in the way the other is cared for.',
			'Loving is building a shared future, where both dreams intertwine, forming a life together full of love.',
			'Love is always a choice, a daily decision to care for, value, and make the relationship grow.',
			'In love, the happiness of the other is your own happiness, because what you desire most is to see them well.',
			'Loving is an act of surrender, where both parties commit to share all they are and have.',
			'Love is the driving force of life, the reason why we do everything possible to make others happy.',
			'In love, words are only a small part of what is expressed; what’s important are the gestures and actions.',
			'Loving is feeling that, with that person, the world makes sense, that no matter what happens, as long as you’re together.',
			'Love is finding a safe place in the arms of someone who accepts you just as you are.',
			'Loving is being able to see the world through the other’s eyes, understanding their desires and fears.',
			'Love is a connection that goes beyond words, in which gestures and glances say it all.',
			'In love, the little details are what matter most, because they show how much the other means to you.',
			'Loving is walking through life together, no matter the adversities, with the certainty that you will always be there for each other.',
			'Love is when time seems to stop when you’re with that person, because every second is precious.',
			'In love, trust is the foundation that allows both to be vulnerable without fear of being judged or hurt.',
			'Loving is discovering that the other’s happiness is your greatest joy, and doing everything possible to see it fulfilled.',
			'Love is a commitment that is renewed every day, based on respect, understanding, and the mutual desire to grow together.',
			'Loving is knowing that the other person is willing to be by your side in both good and bad times.',
			'Love is a dance between two hearts that synchronize effortlessly, but with deep mutual understanding.',
			'In love, words are only the tip of the iceberg; the most important are the actions that show your devotion.',
			'Loving is offering a refuge in times of storm, a place where the other can find comfort and peace.',
			'Love is that moment when you know you’ve found someone with whom you want to share your entire life.',
			'In love, being yourself is enough, because the other values you just as you are, without expectations.',
			'Loving is learning to accept differences, because it’s those differences that enrich the relationship.',
			'Love is that bond that doesn’t break, no matter the distance or circumstances, it always stays strong.',
			'In love, forgiveness is essential, because no one is perfect, but true love always overcomes imperfections.',
			'Loving is choosing someone every day, despite obstacles, because you want to share your life with that person.',
			'Love is knowing that every small gesture of affection has a deep meaning that strengthens the relationship.',
			'In love, mutual respect is the cornerstone; without it, any relationship is doomed to fail.',
			'Loving is accepting that, even if you don’t always understand the other, you will always be willing to support them unconditionally.',
			'Love is building a future together, dreaming, planning, and fighting for what you both want to achieve.',
			'Loving is being willing to make sacrifices for the other, knowing that the well-being of the partner is more important than anything.',
			'In love, every day is an opportunity to show the other how much you care, through words and actions.',
			'Loving is sharing moments of joy and sadness, knowing you’ll be there with that person every step of the way.',
			'Love is trusting each other without reservation, believing that together you can face any adversity.',
			'In love, empathy is key, because it allows you to understand the other’s needs and emotions without the need for words.',
			'Loving is enjoying the little things, like holding hands on a walk or a knowing look, because those are the most precious moments.',
			'Love is that feeling that makes everything else in the world irrelevant when you’re with the right person.',
			'In love, it doesn’t matter what the future holds, because you’ll always have someone with whom to face every challenge.',
			'Loving is finding beauty in the other’s imperfection, because it’s that imperfection that makes them unique and special.',
			'Love is a never-ending journey, where every day you discover yourself and the other in new ways.',
			'In love, open and sincere communication is vital, because only this way can misunderstandings be resolved and the relationship strengthened.',
			'Loving is being able to make the other feel loved without the need for words, only with your actions and presence.',
			'Love is a space where vulnerability is accepted, and where each person can be their true essence without fear of rejection.',
			'In love, small surprises and details keep the relationship alive and full of excitement.',
			'Loving is being the faithful companion who will always be there, ready to walk together toward the future with hope and love.',
			'Love is that invisible bond that unites two people, creating a deeper connection than words can describe.',
			'In love, every conflict is an opportunity to learn and grow, not to separate, but to strengthen the relationship.',
			'Loving is the certainty that, despite difficulties, the other will always be your refuge and support.',
			'Love is the magic that transforms the ordinary into the extraordinary, simply by sharing it with the person you love.',
			'In love, patience is essential, because it allows the relationship to grow solid and lasting over time.',
			'Loving is creating memories together that become treasures you keep for a lifetime.',
			'Love is a feeling that is not measured in words, but in actions that demonstrate how deeply you can love.',
			'In love, emotions flow naturally, creating a harmony that only two hearts can understand.',
			'Loving is giving yourself completely to someone who also gives in the same way, creating a deep and unbreakable bond.',
			'Love is when, just by looking at that person, you know everything will be okay, no matter what happens.',
			'In love, mutual respect is the foundation of any successful relationship, because without it, love loses its strength.',
			'Loving is sharing dreams and hopes, knowing that together you can make them come true.',
			'Love is that feeling that inspires you to be better every day, not just for yourself, but for the other.',
			'In love, every shared laugh, every moment together, becomes a gift you treasure forever.',
			'Loving is learning to let go of fear and insecurity, and to trust fully in the person by your side.',
			'Love is when simply being with that person gives you peace and joy, no matter what happens.',
			'In love, time doesn’t matter, because every moment shared with that person is valuable and irreplaceable.',
			'Loving is learning to give without expecting anything in return, because the mere act of making the other happy is enough.',
			'Love is having a life partner with whom to share every corner of your soul, without reservations or fears.',
			'In love, moments of silence together are as valuable as words, because it is in them that a deep connection is forged.',
			'Loving is being willing to grow together, facing every stage of life as a team that supports each other.',
			'Love is finding comfort in the other’s presence, even without saying a word, just knowing they’re there.',
			'In love, loyalty is essential, because without it, trust and intimacy fade away.',
			'Loving is being able to see the best in the other, even when life is difficult and full of obstacles.',
			'Love is when a look, a gesture, or a smile from that person is enough to improve your day.',
			'In love, effort and dedication are key to keeping the spark alive that makes everything worthwhile.',
			'Loving is when the other becomes such a deep part of your life that it’s impossible to imagine it without them.',
			'Love is when two people choose each other despite everything, because they understand each other in a way that no one else could.',
			'In love, it’s not about being perfect, but about being perfect for each other, with all their flaws.',
			'Loving is living each day as a new opportunity to show that person how much you care and how much you value them.',
			'Love is when you realize that not only do you love that person, but you also want them to be happy.',
			'In love, sharing your insecurities and fears strengthens the bond, because both take care of and protect each other.',
			'Loving is discovering that true happiness lies in seeing the other achieve their dreams, with your unconditional support.',
			"Love is when you feel at home, no matter where you are, as long as you're with that person.",
			'In love, trust is something that is built over time, but once it is established, it is unbreakable.',
			'Loving is having someone who makes you feel unique and special, no matter what the world thinks of you.',
			'Love is knowing that the person by your side will always understand you, even when you can’t express yourself with words.',
			'In love, every day is an opportunity to build memories that, over time, become the foundation of a life together.',
			'Loving is seeing the beauty in the other’s imperfections, because it’s those imperfections that make them perfect for you.',
			'Love is that silent force that can change everything, making even the hardest moments bearable.',
			'In love, every little gesture counts, because it’s the sum of those gestures that makes the relationship grow.',
			'Loving is knowing that, no matter what happens, you will always have someone who will be there for you, regardless of the circumstances.',
			'Love is that inexplicable connection that makes you feel complete, as if everything in the world is in its place.',
			'Loving is seeing the other as an extension of yourself, sharing dreams, fears, and hopes in perfect harmony.',
			'Love is when, even in the darkest moments, you know that the light of the other will always guide you.',
			'In love, the true value is in being able to support the other without expecting anything in return.',
			'Loving is choosing every day to be by their side, building a future together, step by step, without rushing.',
			'Love is that feeling that makes everything else in the world fade away when you are with the right person.',
			'In love, shared silences are as powerful as words, because they express what cannot be said.',
			'Loving is recognizing the beauty in everyday moments, when you share them with someone who makes you feel special.',
			'Love is that refuge where you find comfort, understanding, and support, no matter what the world has in store for you.',
			'In love, there are no secrets, because both trust and open up completely, without fear of being vulnerable.',
			'Loving is feeling that you are part of something bigger, a bond that connects you with the soul of another being.',
			'Love is when two people choose each other, not only for what they are, but for what they can become together.',
			'In love, one’s happiness is the other’s happiness, sharing achievements, dreams, and overcoming challenges as a team.',
			'Loving is feeling that, despite difficulties, there is always hope and enough love to overcome any obstacle.',
			'Love is when both understand each other without words, when gestures and glances say more than any conversation.',
			'In love, trust is earned over time, and strengthened with every challenge you overcome together.',
			'Loving is being the calm in the other’s storm, offering comfort and support when they need it most.',
			'Love is knowing that, even in solitude, you have someone in your heart who accompanies and understands you.',
			'In love, gratitude is essential, because every shared moment is a gift that should be valued and cherished.',
			'Loving is, finally, finding peace in the other’s company, knowing that no matter what happens, you will always be together,.',
		],
		'es_ES' => [
			'Amar es encontrar en el otro un refugio, un lugar seguro donde compartir tus miedos, sueños y esperanzas.',
			'El amor no es solo un sentimiento, es una elección diaria de cuidarse y crecer juntos en armonía.',
			'El amor verdadero es paciencia, comprensión y la voluntad de superar juntos cualquier obstáculo que se cruce en el camino.',
			'En el amor, los momentos simples son los más valiosos: una sonrisa, una mirada, un abrazo que lo dice todo.',
			'Amar no es encontrar a alguien perfecto, sino alguien con quien construir una vida llena de aceptación y respeto mutuo.',
			'El amor es compartir silencios cómodos, esos donde no hace falta hablar para sentir la conexión profunda entre ambos.',
			'Amar es acompañarse en los momentos difíciles, ser la fuerza del otro cuando la vida se vuelve incierta.',
			'El amor verdadero no se mide en palabras, sino en acciones que demuestran un compromiso profundo y sincero.',
			'En el amor romántico, las diferencias enriquecen, pues juntos aprenden a ver el mundo con una perspectiva más amplia.',
			'Amar es ser vulnerable, abrir el corazón sin miedo a ser herido, confiando plenamente en la otra persona.',
			'El amor no es solo una emoción, sino un compromiso constante de apoyo, respeto y la voluntad de crecer juntos.',
			'En el amor, los pequeños gestos hablan más que las grandes promesas; un abrazo, un gesto sincero, una mirada.',
			'Amar es encontrar paz en los brazos de alguien que te entiende sin necesidad de explicaciones ni palabras.',
			'El amor no se trata de ser perfectos, sino de aceptarse y crecer juntos, superando juntos las imperfecciones.',
			'El amor verdadero no solo se ve en los momentos felices, sino en cómo se apoya al otro en dificultades.',
			'En el amor, la confianza es clave. Cuando confías plenamente, todo lo demás en la relación fluye con facilidad.',
			'Amar es saber que, incluso en silencio, ambos pueden encontrar consuelo y fortaleza en la presencia del otro.',
			'El amor romántico es una aventura, un viaje de descubrimiento constante sobre el otro y sobre uno mismo.',
			'Amar es estar dispuesto a hacer sacrificios, pero también a recibir con gratitud todo lo que el otro ofrece.',
			'El amor verdadero es dar sin esperar nada a cambio, porque lo más importante es la felicidad del otro.',
			'El amor romántico es como una danza, donde dos personas se mueven al mismo ritmo, equilibrándose entre sí.',
			'Amar es sentir que, al estar con esa persona, todo tiene más sentido, como si todo encajara en su lugar.',
			'En el amor, las diferencias no separan; las abrazan, convirtiéndolas en algo hermoso que enriquece la relación.',
			'El amor es la base sobre la que se construye una vida llena de momentos compartidos y recuerdos inolvidables.',
			'El amor no es perfecto, pero en su imperfección se encuentra su verdadera belleza, esa que te hace crecer.',
			'Amar es aprender a comunicarte incluso en los silencios, entendiendo que a veces, las palabras no son necesarias.',
			'El amor es la confianza que se construye con el tiempo, fortaleciéndose a través de cada gesto y acción sincera.',
			'Amar es estar dispuesto a invertir tiempo y esfuerzo, construyendo una relación sólida que resista las adversidades de la vida.',
			'En el amor, cada día es una oportunidad para elegir ser mejor, para cuidar y valorar al otro profundamente.',
			'El amor romántico es un espacio donde ambos pueden ser auténticos, sin miedo al juicio, sabiendo que se aceptan.',
			'Amar es crear recuerdos juntos, esos momentos simples que se convierten en los más valiosos con el paso del tiempo.',
			'El amor verdadero es apoyar a la otra persona en sus sueños, alentándola a crecer y a ser su mejor versión.',
			'El amor es la paciencia en los días difíciles, el apoyo cuando las cosas no van bien, sin dudar ni un segundo.',
			'Amar es compartir tus pensamientos, tus miedos y tus alegrías, sabiendo que el otro te escucha y te entiende.',
			'El amor es como un jardín que crece con cuidado, paciencia y dedicación, floreciendo en momentos de ternura compartida.',
			'El amor romántico se trata de ser un equipo, trabajando juntos para superar todo lo que la vida trae consigo.',
			'En el amor, las emociones fluyen con libertad, sin miedo a ser vulnerables o a mostrar lo más profundo de uno mismo.',
			'Amar es no temer al futuro, porque sabes que, con esa persona, cualquier desafío será más fácil de enfrentar.',
			'El amor romántico se alimenta de confianza y respeto, creando una base sólida que resiste cualquier tormenta que se presente.',
			'Amar es mirar al otro y ver no solo lo que es, sino también lo que puede llegar a ser.',
			'El amor es un viaje compartido, donde el destino final importa menos que las experiencias que se viven juntos.',
			'En el amor, cada gesto de cariño, por pequeño que sea, tiene el poder de fortalecer el vínculo entre dos personas.',
			'Amar es ofrecer lo mejor de ti, sabiendo que en una relación verdadera, ambos se entregan con igual sinceridad.',
			'El amor no se trata de encontrar a alguien que te complete, sino de encontrar a alguien con quien ser completo.',
			'El amor romántico se trata de crecer juntos, aprendiendo de cada error, celebrando cada éxito y apoyándose siempre.',
			'Amar es aceptar a la otra persona tal como es, con todos sus defectos, fortalezas, imperfecciones y virtudes.',
			'El amor romántico no se mide por los días, sino por los momentos compartidos y la calidad de la conexión.',
			'Amar es encontrar a alguien con quien compartir no solo los buenos tiempos, sino también los desafíos de la vida.',
			'El amor es estar juntos, no solo en los momentos de felicidad, sino también en los de tristeza y dificultad.',
			'En el amor, la complicidad lo es todo: saber que el otro te entiende sin tener que decir una palabra.',
			'Amar es aceptar la vulnerabilidad, confiar en el otro y saber que, pase lo que pase, siempre estarán juntos.',
			'El amor es la magia que sucede cuando dos personas se entienden sin necesidad de explicar todo a detalle.',
			'Amar es cuidar al otro incluso en los días en que no se sienten lo mejor, mostrando apoyo y comprensión.',
			'El amor verdadero es ese que no busca cambiar al otro, sino que lo celebra tal como es, con todos sus matices.',
			'En el amor romántico, cada día tiene su propia belleza, aunque no sea perfecto, porque lo importante es la compañía.',
			'Amar es reconocer en el otro un refugio donde uno puede ser uno mismo, sin miedo a ser juzgado.',
			'El amor es saber que, sin importar las diferencias, siempre hay un lugar para el entendimiento y la empatía mutua.',
			'Amar es compartir tu vida con alguien que te elige todos los días, sin importar las circunstancias ni los obstáculos.',
			'En el amor, el respeto y la confianza son los pilares fundamentales que sostienen la relación, permitiéndole crecer y prosperar.',
			'Amar es ver la belleza de la vida a través de los ojos de la persona que amas, compartiendo cada instante.',
			'El amor es la capacidad de comprender, perdonar y aceptar al otro, incluso cuando las circunstancias son difíciles de afrontar.',
			'Amar es crear un lazo tan fuerte que ni el tiempo ni las dificultades puedan romperlo, siempre perseverando juntos.',
			'El amor es dar sin esperar, porque lo más importante es ver al otro feliz y completo a tu lado.',
			'Amar es saber que no importa cuán complicado sea el día, siempre puedes contar con el apoyo incondicional del otro.',
			'El amor romántico es esa sensación de seguridad que encuentras en la persona que más te importa, sin importar nada más.',
			'En el amor, las promesas se cumplen con hechos, no solo con palabras; son los gestos los que verdaderamente importan.',
			'Amar es ser capaz de ser vulnerable, mostrar tu corazón y saber que será protegido por la persona que amas.',
			'El amor es encontrar en el otro a alguien que te hace sentir completo, que te hace ser mejor cada día.',
			'En el amor, no se trata de perderse en el otro, sino de crecer juntos, respetando la individualidad de ambos.',
			'Amar es disfrutar de la compañía, de los pequeños momentos, de la sencillez de estar juntos sin necesidad de hacer más.',
			'El amor romántico es esa sensación de saber que siempre hay alguien esperando por ti, dispuesto a apoyarte en todo.',
			'Amar es compartir la vida con alguien que te haga sentir especial, que valore cada momento y cada detalle.',
			'En el amor, cada palabra se siente como un abrazo, cada gesto como un testamento de cariño sincero e incondicional.',
			'El amor verdadero es sentir que, sin importar lo que pase, el otro siempre estará allí, firme y presente.',
			'Amar es no solo querer a alguien, sino también respetar sus sueños, sus metas y sus deseos más profundos.',
			'El amor es la sensación de paz que llega cuando encuentras a alguien que te entiende sin necesidad de palabras.',
			'El amor romántico es cuando dos personas se convierten en una, compartiendo todo, sin perder su individualidad ni su esencia.',
			'Amar es aceptar los altibajos de la vida, sabiendo que, juntos, pueden superar cualquier adversidad con amor y comprensión.',
			'El amor es la entrega constante, no solo en palabras, sino en acciones que demuestran cuánto te importa esa persona.',
			'En el amor, cada conflicto es una oportunidad para crecer juntos, aprender más sobre el otro y fortalecer la relación.',
			'Amar es encontrar paz en la presencia del otro, sentir que, con ellos, todo lo demás puede esperar.',
			'El amor es la capacidad de mirar al otro y ver en sus ojos un reflejo de tus propios sueños.',
			'Amar es querer compartir todos tus días, desde los más felices hasta los más difíciles, con esa persona especial.',
			'El amor romántico es confiar plenamente, sabiendo que el otro siempre estará ahí para apoyarte y levantarte cuando caigas.',
			'En el amor, el tiempo no importa tanto; lo que cuenta es la calidad de los momentos compartidos juntos.',
			'Amar es sentir que, al mirar a los ojos de alguien, puedes ver tu futuro reflejado en sus pupilas.',
			'El amor es cuando dos personas deciden ser fuertes juntos, porque saben que la fuerza de uno fortalece al otro.',
			'Amar es un viaje lleno de desafíos, pero también de momentos de alegría, amor y la constante construcción de algo hermoso.',
			'El amor es saber que, aunque el mundo cambie, la conexión con esa persona siempre será un ancla en tu vida.',
			'Amar es construir juntos una historia de vida, llena de risas, desafíos, abrazos y recuerdos que perduran en el tiempo.',
			'El amor es la libertad de ser uno mismo, sin miedo al juicio, porque el otro siempre te acepta tal como eres.',
			'Amar es acompañar al otro en sus sueños y desafíos, siendo su compañero y su mayor apoyo en todo momento.',
			'El amor romántico es encontrar en la otra persona una razón para sonreír, incluso en los días más oscuros.',
			'Amar es compartir los sueños, temores y esperanzas con alguien que te escucha y te apoya en cada paso.',
			'El amor es saber que, aunque no siempre haya respuestas, la presencia del otro basta para encontrar consuelo.',
			'En el amor, no importa cuántas veces te caigas, lo que importa es que siempre habrá alguien allí para levantarte.',
			'Amar es hacer que la vida del otro sea un poco más fácil, más feliz y más significativa con cada acción.',
			'El amor es la tranquilidad de saber que, sin importar qué, siempre tendrás a alguien con quien compartir todo.',
			'El amor verdadero es ver a la otra persona no solo con los ojos, sino también con el corazón.',
			'Amar es entregarse sin reservas, pero también recibir con gratitud todo lo que el otro tiene para ofrecer.',
			'El amor es saber que, sin importar las dificultades, siempre podrás contar con el apoyo incondicional de esa persona especial.',
			'Amar es entregarse sin miedo, confiar en el otro y sentir que juntos son más fuertes que cualquier adversidad.',
			'El amor es una aventura constante, donde el destino es incierto, pero la compañía del otro siempre da paz.',
			'En el amor, lo más importante no es lo que recibimos, sino lo que damos a la persona que amamos.',
			'Amar es hacer que el otro se sienta único, especial, y apreciado, mostrándole lo valioso que es en tu vida.',
			'El amor verdadero se alimenta de la confianza mutua, la paciencia y el entendimiento, creando un lazo irrompible.',
			'Amar es ver en el otro un reflejo de tus propios sueños, miedos y deseos, y abrazarlos juntos.',
			'El amor no se trata solo de emociones, sino de acciones diarias que demuestran el cariño y la dedicación.',
			'Amar es sentirte en paz contigo mismo cuando estás con esa persona, sabiendo que no hay lugar más seguro.',
			'El amor romántico es la magia que ocurre cuando dos personas se eligen mutuamente, día tras día, con el corazón.',
			'Amar es no solo estar juntos en los buenos momentos, sino también estar dispuestos a apoyarse en los momentos difíciles.',
			'El amor es ser capaz de mirar al otro y, en su mirada, ver reflejados tus propios sueños y esperanzas.',
			'En el amor, lo más valioso es la comprensión silenciosa, esa capacidad de entender sin necesidad de palabras.',
			'El amor es el compromiso de seguir creciendo juntos, aprendiendo de los errores y celebrando los logros en pareja.',
			'Amar es dar sin esperar, es la satisfacción de ver a la otra persona feliz por tu simple presencia.',
			'El amor verdadero es confiar sin dudar, es sentir que nada puede separarlos porque están conectados profundamente.',
			'En el amor, las palabras son importantes, pero los gestos, las acciones y la dedicación mutua son lo que realmente cuenta.',
			'Amar es aprender a compartir la vida, los sueños y los miedos, sabiendo que ambos se apoyan sin reservas.',
			'El amor romántico es un viaje de descubrimiento continuo, donde cada día te sorprendes al conocer más profundamente a tu pareja.',
			'Amar es sentir que, con esa persona a tu lado, todo parece más fácil, más sencillo y lleno de luz.',
			'El amor es comprender que el verdadero compromiso no se mide por las palabras, sino por las acciones constantes.',
			'En el amor, cada pequeño gesto cuenta: un beso, un abrazo, una caricia, todos son huellas que marcan el alma.',
			'Amar es estar dispuesto a construir un futuro juntos, sabiendo que la felicidad del otro es parte de la propia.',
			'El amor es la fuerza que te impulsa a ser mejor, a superar tus miedos y a lograr tus sueños.',
			'Amar es compartir tus momentos más íntimos, tus pensamientos más profundos, y encontrar en el otro una respuesta comprensiva.',
			'El amor verdadero es cuando dos personas se eligen mutuamente, no por necesidad, sino porque realmente se quieren y se valoran.',
			'Amar es aprender a aceptarse mutuamente, con todas las diferencias y peculiaridades, sabiendo que lo que importa es el vínculo.',
			'El amor es un refugio en tiempos de tormenta, donde puedes encontrar consuelo, fuerza y la esperanza para seguir adelante.',
			'En el amor, la sinceridad es fundamental. Ser transparente y auténtico es la base para construir una relación sólida.',
			'Amar es entregar todo lo que tienes, sin reservas, sabiendo que la otra persona hará lo mismo por ti.',
			'El amor es un lenguaje sin barreras, un diálogo constante de miradas, gestos y pequeños detalles que fortalecen la relación.',
			'Amar es saber que, sin importar el tiempo o las circunstancias, siempre tendrás un lugar especial en el corazón del otro.',
			'En el amor romántico, la honestidad es esencial; compartir lo que sentimos y pensamos nos acerca y fortalece la relación.',
			'Amar es sentir que el corazón late más fuerte cuando estás cerca de esa persona, como si el mundo se detuviera.',
			'El amor no busca cambiar al otro, sino aceptarlo y acompañarlo en su camino de crecimiento personal y conjunto.',
			'Amar es aprender a perdonar, dejar ir los rencores y seguir adelante, siempre con la voluntad de fortalecer el amor.',
			'El amor es cuando una mirada puede decir todo lo que las palabras no pueden expresar, todo lo que sientes.',
			'En el amor, cada día es una oportunidad para hacer sentir especial al otro, para demostrar lo valioso que es.',
			'Amar es ser el refugio del otro, la persona en quien se confía plenamente, sin miedos ni reservas.',
			'El amor romántico es un pacto silencioso de respeto y lealtad, donde dos personas se eligen sin condiciones ni dudas.',
			'Amar es tener la seguridad de que, a pesar de las dificultades, siempre estarás junto a la persona que amas.',
			'El amor es descubrir que no necesitas ser perfecto, porque la persona que te ama te acepta tal como eres.',
			'En el amor, la paciencia es clave. Saber esperar, dar espacio y tiempo para que la relación crezca y se fortalezca.',
			'Amar es caminar al lado del otro, hombro con hombro, enfrentando juntos lo que la vida les tenga preparado.',
			'El amor romántico es el arte de hacer sentir al otro único y especial, a través de gestos y palabras sinceras.',
			'Amar es ser testigo de la evolución de la otra persona, viendo cómo se transforma y creciendo juntos en el proceso.',
			'En el amor, la confianza es fundamental. Saber que el otro está allí, dispuesto a apoyarte, sin importar lo que pase.',
			'Amar es compartir tus miedos y tus alegrías, con la certeza de que el otro siempre estará dispuesto a escucharte.',
			'El amor es esa chispa que ilumina la vida cotidiana, convirtiendo lo mundano en algo hermoso cuando se comparte con alguien especial.',
			'Amar es no temer ser vulnerable, porque sabes que el otro te cuida y te respeta tal como eres.',
			'El amor es una promesa no escrita, pero vivida en cada acción y decisión que tomamos junto a esa persona.',
			'En el amor, la complicidad es fundamental. Ser capaces de entendernos con una mirada, sin necesidad de palabras, fortalece la relación.',
			'Amar es creer en el otro, en su potencial, en sus sueños, y apoyarlo para que logre todo lo que desea.',
			'El amor verdadero no se mide por lo que se da o recibe, sino por lo que se construye juntos.',
			'Amar es aprender a disfrutar de los pequeños momentos, porque son esos los que realmente fortalecen la relación a largo plazo.',
			'El amor es el compromiso de estar juntos en todo, no solo cuando todo va bien, sino también en los momentos difíciles.',
			'En el amor romántico, lo más importante es la conexión emocional, esa que no necesita palabras, solo la presencia del otro.',
			'Amar es aprender a escuchar, no solo con los oídos, sino también con el corazón, entendiendo lo que no se dice.',
			'El amor es ser compañeros de vida, compartiendo tanto los momentos felices como los desafíos, siempre con el apoyo mutuo.',
			'Amar es construir una vida juntos, sabiendo que, a pesar de las dificultades, siempre hay algo que los une profundamente.',
			'En el amor, la confianza y el respeto mutuo son las bases que sostienen una relación sólida y duradera.',
			'Amar es la libertad de ser tú mismo, sin miedo al juicio, porque el otro te acepta con todo lo que eres.',
			'El amor romántico es el refugio donde te encuentras a ti mismo, mientras te entregas por completo al otro.',
			'Amar es construir un vínculo que resista las adversidades, que se fortalezca con cada desafío y que se renueve constantemente.',
			'En el amor, cada sacrificio vale la pena, porque al final, lo que importa es la felicidad de la persona amada.',
			'Amar es un compromiso continuo de cuidado, respeto y dedicación, donde cada día se hace un esfuerzo por mejorar la relación.',
			'El amor es cuando encuentras en alguien no solo una pareja, sino un verdadero amigo con quien compartir todo.',
			'Amar es elegir caminar juntos, independientemente de los obstáculos, siempre confiando en el apoyo incondicional del otro.',
			'En el amor, la comunicación abierta y sincera es fundamental, ya que permite resolver malentendidos y fortalecer la conexión emocional.',
			'Amar es un acto de generosidad, de dar lo mejor de ti para hacer feliz a la otra persona.',
			'El amor romántico es la fuerza que impulsa a dos personas a superar sus miedos y a lograr grandes cosas juntos.',
			'Amar es saber que, aunque el futuro sea incierto, el presente compartido con esa persona es todo lo que necesitas.',
			'En el amor, los momentos compartidos se vuelven recuerdos que atesoramos para siempre, construyendo juntos una historia de vida.',
			'Amar es cuidar al otro en su totalidad, en cuerpo, mente y alma, y ser su refugio cuando lo necesite.',
			'El amor es la valentía de ser vulnerable, de mostrar quién eres realmente y saber que el otro te acepta.',
			'Amar es hacer del otro una prioridad en tu vida, porque su felicidad es tan importante como la tuya.',
			'El amor es aprender a crecer juntos, a evolucionar como pareja, mientras se mantienen firmes en los valores que comparten.',
			'Amar es saber que no importa lo que suceda, siempre tendrán un lugar especial en el corazón del otro.',
			'En el amor, cada gesto cuenta, cada palabra, cada acción, y todas son una forma de demostrar cuánto te importa.',
			'Amar es hacer que la vida del otro sea más fácil, más alegre y más significativa con cada acción y palabra.',
			'El amor romántico es el acto de compartir los momentos más íntimos y personales, creando una conexión profunda y única.',
			'Amar es ser capaz de ver en los ojos del otro una vida llena de sueños, desafíos y esperanzas.',
			'En el amor, cada día es una oportunidad para hacer feliz a la persona que amas, para mostrarle tu cariño.',
			'Amar es ser el refugio y la fortaleza del otro, la persona en quien siempre pueden confiar, pase lo que pase.',
			'El amor es una danza constante entre dar y recibir, entre ser fuerte y vulnerable, siempre creciendo juntos como pareja.',
			'Amar es entender que el otro tiene sus propios miedos y sueños, y estar dispuesto a acompañarlo en su camino.',
			'El amor es la certeza de que, sin importar las circunstancias, siempre tendrás a alguien con quien compartir tu vida.',
			'En el amor, la lealtad y la honestidad son los pilares fundamentales sobre los que se construye una relación duradera.',
			'Amar es vivir cada día con el deseo de hacerle la vida más fácil, más feliz y más plena al otro.',
			'El amor es cuando dos personas se encuentran en el momento justo, creando un vínculo único que no puede romperse.',
			'En el amor, cada conflicto es una oportunidad para crecer, aprender y fortalecer el vínculo entre dos personas que se quieren.',
			'Amar es saber que, pase lo que pase, siempre tendrás un hogar en los brazos de esa persona especial.',
			'El amor es una promesa de apoyo constante, de estar ahí para el otro sin importar las circunstancias que enfrenten juntos.',
			'Amar es un viaje que se disfruta en el presente, con la mirada puesta en el futuro que construirán juntos.',
			'En el amor, cada sacrificio hecho por el bienestar del otro se convierte en una muestra de lo profundo que es el cariño.',
			'Amar es aprender a encontrar belleza en las imperfecciones del otro, sabiendo que es lo que los hace únicos y especiales.',
			'El amor es compartir las emociones, los desafíos y los logros, porque juntos son más fuertes que separados.',
			'Amar es saber que el otro siempre estará allí, dispuesto a brindarte su amor, apoyo y comprensión en cualquier momento.',
			'El amor es la tranquilidad de saber que, con esa persona, el mundo parece un lugar más amable y lleno de esperanza.',
			'En el amor, cada detalle cuenta, cada palabra, cada gesto, porque todos contribuyen a fortalecer el vínculo entre dos personas que se aman.',
			'Amar es la certeza de que, a pesar de las diferencias, siempre hay algo que los une: un profundo amor y respeto.',
			'El amor es comprender al otro en su totalidad, aceptando sus defectos, fortalezas, sueños y miedos, sin querer cambiar nada de él.',
			'Amar es aprender a cuidar del otro, a preocuparse por su bienestar y a brindarle apoyo incondicional cuando lo necesita.',
			'El amor es una relación de crecimiento mutuo, donde ambos se impulsan a ser mejores y alcanzar sus sueños juntos.',
			'En el amor, no se trata de ser perfecto, sino de ser auténtico, sincero y verdadero el uno con el otro.',
			'Amar es compartir la vida con alguien que te entiende, te respeta y te valora por lo que eres.',
			'El amor es saber que, aunque todo cambie, siempre habrá algo constante: el compromiso y el cariño compartido entre ambos.',
			'Amar es sentirse en casa, no solo en el espacio físico, sino en los brazos y el corazón de esa persona.',
			'El amor es el deseo de ver al otro crecer, ser feliz y realizar sus sueños, siempre apoyándolo sin reservas.',
			'En el amor, la confianza es clave para construir una relación sólida y duradera, una base que resista cualquier prueba.',
			'Amar es compartir los pequeños momentos cotidianos, porque en ellos se encuentran las semillas de una relación profunda y duradera.',
			'El amor es cuando dos personas se eligen mutuamente, sin promesas de perfección, pero con la voluntad de ser mejores juntos.',
			'En el amor, la empatía y la comprensión son esenciales, porque nos permiten ver el mundo desde los ojos del otro.',
			'Amar es caminar juntos en la vida, paso a paso, enfrentando juntos cada desafío que el destino les traiga.',
			'El amor es no solo un sentimiento, sino una decisión constante de hacer que la otra persona se sienta especial y amada.',
			'Amar es compartir tu vida con alguien que te apoya, te comprende y te da espacio para ser quien eres.',
			'El amor es la fuerza que nos impulsa a cuidar de alguien más allá de nosotros mismos, poniéndolos antes que nada.',
			'En el amor, la dedicación y el compromiso mutuo son lo que hacen que la relación se fortalezca y crezca con el tiempo.',
			'Amar es tener la certeza de que, sin importar lo que pase, siempre podrán superar cualquier obstáculo juntos.',
			'El amor es cuando dos personas se apoyan mutuamente para alcanzar sus sueños, sin miedo a las dificultades que puedan surgir.',
			'Amar es elegirte todos los días, no por obligación, sino porque en el otro encuentras todo lo que necesitas.',
			'En el amor, la aceptación es fundamental. Aceptar al otro tal como es, sin tratar de cambiarlo, fortalece la relación.',
			'El amor es compartir tus miedos, sueños y esperanzas, sabiendo que, con el apoyo del otro, todo será posible.',
			'Amar es una conexión profunda que va más allá de lo físico; es compartir almas y corazones, sin miedos ni reservas.',
			'El amor es cuando una sonrisa de esa persona te hace sentir que todo en el mundo está bien.',
			'En el amor, la paciencia es importante. Aprender a esperar y confiar en el proceso es esencial para una relación duradera.',
			'Amar es ser capaz de poner en primer lugar el bienestar del otro, sabiendo que su felicidad también será la tuya.',
			'El amor es descubrir juntos nuevos horizontes, construir un futuro compartido, y disfrutar de cada paso dado en pareja.',
			'En el amor, las pequeñas cosas importan más de lo que parece, porque son los detalles los que hacen la diferencia.',
			'Amar es caminar en sincronía, como dos piezas que encajan perfectamente en el puzzle de la vida.',
			'El amor es siempre estar dispuesto a hacer sacrificios por el otro, porque la felicidad de la pareja es prioridad.',
			'En el amor, la vulnerabilidad se convierte en una fuerza, porque permite que el otro vea tu verdadero ser.',
			'Amar es aprender que el amor no siempre es perfecto, pero la belleza radica en la capacidad de superarlo todo.',
			'El amor es ese refugio seguro donde puedes ser tú mismo, sin máscaras ni miedos, sabiendo que eres aceptado.',
			'En el amor, el respeto mutuo y la comprensión son los pilares que mantienen fuerte y sana la relación.',
			'Amar es sentir que, con esa persona a tu lado, el futuro no parece tan incierto ni tan temido.',
			'El amor es la promesa de caminar juntos en todas las estaciones de la vida, disfrutando tanto de las flores como de las tormentas.',
			'Amar es cuando, incluso en los días grises, esa persona logra sacar una sonrisa en tu rostro con solo mirarte.',
			'El amor es cuando encuentras a alguien con quien compartir tu alma, y esa conexión se convierte en algo eterno.',
			'En el amor, lo más hermoso es la complicidad, el entendimiento mutuo sin palabras, la paz que se encuentra en los gestos.',
			'Amar es un viaje donde cada día es una nueva aventura, y cada momento juntos se convierte en un recuerdo inolvidable.',
			'El amor es ese impulso que te lleva a cuidar de alguien, a hacer todo lo posible por verlo feliz.',
			'En el amor, no existe el miedo, porque cuando amas, sabes que siempre habrá un abrazo esperando para consolarte.',
			'Amar es ser conscientes de que juntos pueden construir un amor que sea mucho más fuerte que cualquier dificultad.',
			'El amor es cuando, incluso en medio de la rutina, encuentras momentos mágicos solo con la presencia del otro.',
			'En el amor, cada día es una oportunidad para fortalecer el lazo, para aprender más sobre el otro y sobre uno mismo.',
			'Amar es compartir tus logros y tus fracasos, sabiendo que el otro estará allí para celebrar o consolarte.',
			'El amor es cuando te sientes agradecido por tener a esa persona a tu lado, compartiendo cada momento de tu vida.',
			'En el amor, todo es posible, porque con la fuerza de dos corazones unidos, se pueden lograr grandes cosas.',
			'Amar es ser el apoyo incondicional del otro, ayudándose mutuamente a crecer y evolucionar como personas y como pareja.',
			'El amor es vivir un presente constante, donde lo único que importa es estar juntos, sin pensar demasiado en el futuro.',
			'En el amor, el esfuerzo mutuo para construir un futuro juntos es lo que convierte a la relación en algo sólido.',
			'Amar es reconocer que, aunque el mundo sea incierto, el amor es una constante en la vida de ambos.',
			'El amor es confiar plenamente en el otro, sabiendo que siempre tendrán un lugar especial en los corazones de cada uno.',
			'En el amor, el respeto es esencial, ya que sin él, cualquier relación puede perder su estabilidad y crecimiento.',
			'Amar es estar dispuesto a comprometerte, a ceder, a negociar, pero siempre buscando lo mejor para los dos.',
			'El amor es un reflejo de dos almas que se encuentran, se entienden y se eligen con el corazón y la mente.',
			'En el amor, la belleza no está solo en lo físico, sino en la forma en que se cuida al otro.',
			'Amar es construir un futuro compartido, donde los sueños de ambos se entrelazan, formando una vida juntos y llena de amor.',
			'El amor es siempre una elección, una decisión diaria de cuidar, valorar y hacer crecer la relación.',
			'En el amor, la felicidad del otro es tu propia felicidad, porque lo que más deseas es verlo bien.',
			'Amar es un acto de entrega, en el que ambas partes se comprometen a compartir todo lo que son y tienen.',
			'El amor es el motor que mueve la vida, la razón por la cual hacemos todo lo posible por ver felices a los demás.',
			'En el amor, las palabras son solo una pequeña parte de lo que se expresa; lo importante son los gestos y acciones.',
			'Amar es sentir que, con esa persona, el mundo cobra sentido, que no importa lo que pase mientras estén juntos.',
			'El amor es encontrar un lugar seguro en los brazos de alguien que te acepta tal y como eres.',
			'Amar es ser capaz de ver el mundo con los ojos del otro, entendiendo sus deseos y temores.',
			'El amor es una conexión que va más allá de las palabras, en la que los gestos y miradas lo dicen todo.',
			'En el amor, los pequeños detalles son los que más importan, porque son los que demuestran cuánto te importa el otro.',
			'Amar es caminar juntos por la vida, sin importar las adversidades, con la certeza de que siempre estarán uno para el otro.',
			'El amor es cuando el tiempo parece detenerse cuando estás con esa persona, porque cada segundo es valioso.',
			'En el amor, la confianza es la base que permite a ambos ser vulnerables sin temor a ser juzgados o heridos.',
			'Amar es descubrir que la felicidad del otro es tu mayor alegría, y hacer todo lo posible para verla realizada.',
			'El amor es un compromiso que se renueva cada día, basado en el respeto, la comprensión y el deseo mutuo de crecer juntos.',
			'Amar es saber que la otra persona está dispuesta a estar a tu lado en los buenos y malos momentos.',
			'El amor es una danza entre dos corazones que se sincronizan, sin esfuerzo, pero con una comprensión mutua profunda.',
			'En el amor, las palabras son solo la punta del iceberg; lo más importante son las acciones que demuestran tu devoción.',
			'Amar es ofrecer un refugio en tiempos de tormenta, un lugar donde el otro pueda encontrar consuelo y paz.',
			'El amor es ese momento en el que sabes que has encontrado a alguien con quien quieres compartir toda tu vida.',
			'En el amor, ser uno mismo es suficiente, porque el otro te valora tal y como eres, sin expectativas.',
			'Amar es aprender a aceptar las diferencias, porque son esas diferencias las que enriquecen la relación.',
			'El amor es ese vínculo que no se rompe, no importa la distancia o las circunstancias, siempre permanece fuerte.',
			'En el amor, el perdón es esencial, porque nadie es perfecto, pero el amor verdadero siempre supera las imperfecciones.',
			'Amar es elegir a alguien todos los días, a pesar de los obstáculos, porque quieres compartir tu vida con esa persona.',
			'El amor es saber que cada pequeño gesto de afecto tiene un significado profundo que fortalece la relación.',
			'En el amor, el respeto mutuo es la piedra angular, sin él, cualquier relación está condenada a fracasar.',
			'Amar es aceptar que, aunque no siempre entiendas al otro, siempre estarás dispuesto a apoyarlo incondicionalmente.',
			'El amor es construir un futuro juntos, soñando, planeando y luchando por lo que ambos desean alcanzar.',
			'Amar es ser capaz de hacer sacrificios por el otro, sabiendo que el bienestar de la pareja es más importante que cualquier cosa.',
			'En el amor, cada día es una oportunidad para demostrarle al otro cuánto te importa, a través de palabras y acciones.',
			'Amar es compartir los momentos de alegría y tristeza, sabiendo que estarás junto a esa persona en cada paso.',
			'El amor es confiar el uno en el otro sin reservas, creyendo que juntos pueden enfrentar cualquier adversidad.',
			'En el amor, la empatía es clave, porque permite comprender las necesidades y emociones del otro sin necesidad de palabras.',
			'Amar es disfrutar de las pequeñas cosas, como un paseo de la mano o una mirada cómplice, porque esos son los momentos más preciosos.',
			'El amor es ese sentimiento que hace que todo lo demás en el mundo se vuelva irrelevante cuando estás con la persona adecuada.',
			'En el amor, no importa lo que el futuro depare, porque siempre tendrás a alguien con quien enfrentar cada desafío.',
			'Amar es encontrar belleza en la imperfección del otro, porque es esa imperfección lo que lo hace único y especial.',
			'El amor es un viaje sin fin, donde cada día te descubres a ti mismo y al otro de nuevas maneras.',
			'En el amor, la comunicación abierta y sincera es vital, porque solo así se pueden resolver los malentendidos y fortalecer la relación.',
			'Amar es ser capaz de hacer que el otro se sienta amado sin necesidad de palabras, solo con tus acciones y tu presencia.',
			'El amor es un espacio donde la vulnerabilidad es aceptada, y donde cada persona puede ser su verdadera esencia sin miedo al rechazo.',
			'En el amor, las pequeñas sorpresas y detalles hacen que la relación se mantenga viva y llena de emoción.',
			'Amar es ser el compañero fiel que siempre estará allí, dispuesto a caminar juntos hacia el futuro con esperanza y amor.',
			'El amor es ese lazo invisible que une a dos personas, creando una conexión más profunda que las palabras pueden describir.',
			'En el amor, cada conflicto es una oportunidad para aprender y crecer, no para separarse, sino para fortalecer la relación.',
			'Amar es la certeza de que, a pesar de las dificultades, el otro siempre será tu refugio y apoyo.',
			'El amor es la magia que transforma lo ordinario en extraordinario, simplemente por compartirlo con la persona que amas.',
			'En el amor, la paciencia es fundamental, porque permite que la relación crezca de manera sólida y duradera con el tiempo.',
			'Amar es crear recuerdos juntos, que se convierten en los tesoros que guardas para toda la vida.',
			'El amor es un sentimiento que no se mide en palabras, sino en acciones que demuestran lo profundo que puedes llegar a querer.',
			'En el amor, las emociones fluyen de manera natural, creando una armonía que solo dos corazones pueden entender.',
			'Amar es entregarse por completo a alguien que también se entrega de la misma manera, creando un vínculo profundo e irrompible.',
			'El amor es cuando, con solo mirar a esa persona, sabes que todo estará bien, no importa lo que pase.',
			'En el amor, el respeto mutuo es la base de cualquier relación exitosa, porque sin él, el amor pierde su fuerza.',
			'Amar es compartir los sueños y las esperanzas, sabiendo que juntos pueden hacerlos realidad.',
			'El amor es ese sentimiento que te inspira a ser mejor cada día, no solo por ti, sino por el otro.',
			'En el amor, cada risa compartida, cada momento juntos, se convierte en un regalo que atesoras para siempre.',
			'Amar es aprender a soltar el miedo y la inseguridad, y confiar plenamente en la persona que tienes a tu lado.',
			'El amor es cuando el simple hecho de estar con esa persona te da paz y alegría, sin importar lo que suceda.',
			'En el amor, el tiempo no importa, porque cada momento compartido con esa persona es valioso e irremplazable.',
			'Amar es aprender a dar sin esperar nada a cambio, porque el simple hecho de hacer feliz al otro es suficiente.',
			'El amor es tener un compañero de vida con quien compartir cada rincón de tu alma, sin reservas ni miedos.',
			'En el amor, los momentos de silencio juntos son tan valiosos como las palabras, porque es en ellos donde se forja una conexión profunda.',
			'Amar es estar dispuesto a crecer juntos, enfrentando cada etapa de la vida como un equipo que se apoya mutuamente.',
			'El amor es encontrar consuelo en la presencia del otro, incluso sin decir una palabra, solo sabiendo que están ahí.',
			'En el amor, la lealtad es esencial, porque sin ella, la confianza y la intimidad se desvanecen.',
			'Amar es ser capaz de ver lo mejor del otro, incluso cuando la vida es difícil y llena de obstáculos.',
			'El amor es cuando una mirada, un gesto, o una sonrisa de esa persona es suficiente para que tu día mejore.',
			'En el amor, el esfuerzo y la dedicación son clave para mantener viva la chispa que hace que todo valga la pena.',
			'Amar es cuando el otro se convierte en parte de tu vida de una manera tan profunda que es imposible imaginarla sin él.',
			'El amor es cuando dos personas se eligen a pesar de todo, porque se entienden de una manera que nadie más podría.',
			'En el amor, no se trata de ser perfectos, sino de ser perfectos el uno para el otro, con todos sus defectos.',
			'Amar es vivir cada día como una nueva oportunidad para demostrarle a esa persona cuánto te importa y cuánto la valoras.',
			'El amor es cuando te das cuenta de que no solo amas a esa persona, sino que también quieres que sea feliz.',
			'En el amor, compartir tus inseguridades y miedos fortalece el vínculo, porque ambos se cuidan y protegen mutuamente.',
			'Amar es descubrir que la verdadera felicidad radica en ver al otro alcanzar sus sueños, con tu apoyo incondicional.',
			'El amor es cuando te sientes en casa, no importa donde estés, siempre y cuando estés junto a esa persona.',
			'En el amor, la confianza es algo que se construye con el tiempo, pero una vez que se establece, es irrompible.',
			'Amar es tener a alguien que te haga sentir único y especial, sin importar lo que el mundo piense de ti.',
			'El amor es saber que la persona que tienes a tu lado siempre te comprenderá, incluso cuando no puedas expresarte con palabras.',
			'En el amor, cada día es una oportunidad para construir recuerdos que, con el tiempo, se convierten en la base de una vida juntos.',
			'Amar es ver la belleza en las imperfecciones del otro, porque son esas imperfecciones las que lo hacen perfecto para ti.',
			'El amor es esa fuerza silenciosa que puede cambiarlo todo, haciendo que incluso los momentos más difíciles sean soportables.',
			'En el amor, cada pequeño gesto cuenta, porque es la suma de esos gestos lo que hace que la relación crezca.',
			'Amar es saber que, sin importar lo que pase, siempre tendrás a alguien que estará allí para ti, sin importar las circunstancias.',
			'El amor es esa conexión inexplicable que te hace sentir completo, como si todo en el mundo estuviera en su lugar.',
			'Amar es ver al otro como una extensión de ti mismo, compartiendo sueños, miedos y esperanzas en perfecta armonía.',
			'El amor es cuando, incluso en los momentos más oscuros, sabes que la luz del otro siempre te guiará.',
			'En el amor, el verdadero valor está en ser capaz de apoyar al otro sin esperar nada a cambio.',
			'Amar es elegir todos los días estar a su lado, construyendo un futuro juntos, paso a paso, sin prisas.',
			'El amor es ese sentimiento que hace que todo lo demás en el mundo se desvanezca cuando estás con la persona correcta.',
			'En el amor, los silencios compartidos son tan poderosos como las palabras, porque expresan lo que no puede decirse.',
			'Amar es reconocer la belleza en los momentos cotidianos, cuando lo compartes con alguien que te hace sentir especial.',
			'El amor es ese refugio donde encuentras consuelo, comprensión y apoyo, sin importar lo que el mundo te depare.',
			'En el amor, no existen secretos, porque ambos confían y se abren completamente, sin miedo a ser vulnerables.',
			'Amar es sentir que eres parte de algo más grande, un vínculo que te conecta con el alma de otro ser.',
			'El amor es cuando dos personas se eligen, no solo por lo que son, sino por lo que juntas pueden llegar a ser.',
			'En el amor, la felicidad de uno es la felicidad del otro, compartiendo logros, sueños y superando desafíos como equipo.',
			'Amar es sentir que, a pesar de las dificultades, siempre hay esperanza y amor suficiente para superar cualquier obstáculo.',
			'El amor es cuando ambos se entienden sin palabras, cuando los gestos y miradas dicen más que cualquier conversación.',
			'En el amor, la confianza se gana con el tiempo, y se fortalece con cada desafío que superan juntos.',
			'Amar es ser la calma en la tormenta del otro, ofreciendo consuelo y apoyo cuando más lo necesita.',
			'El amor es saber que, incluso en la soledad, tienes a alguien en tu corazón que te acompaña y te entiende.',
			'En el amor, la gratitud es esencial, porque cada momento compartido es un regalo que hay que valorar y cuidar.',
			'Amar es, finalmente, encontrar la paz en la compañía del otro, sabiendo que no importa lo que pase, siempre estarán juntos.',
		],
	];

	/**
	 * Run the database seeds.
	 */
	public function run(): void
	{
		DB::table($this->galleryTable)->insert([
			'product_type_id' => 26,
		]);

		$contentId = DB::table($this->galleryTable)
			->where('product_type_id', 26)
			->value('id');

		$textElements = count($this->texts['es_ES']);

		for ($i = 0; $i < $textElements; $i++) {
			DB::table($this->textsTable)->insert([
				'gallery_id' => $contentId,
				'en_EN' => $this->texts['en_EN'][$i],
				'es_ES' => $this->texts['es_ES'][$i],
				'order' => $i + 1,
			]);
		}

		foreach ($this->images as $imageUrl) {
			DB::table($this->imagesTable)->insert([
				'gallery_id' => $contentId,
				'url' => $imageUrl,
			]);
		}
	}
}
