CREATE TABLE `nfc` (
					   `id` BIGINT NULL AUTO_INCREMENT PRIMARY KEY,
					   `account_id` BIGINT NULL,
					   `target_url` VARCHAR(2048) NULL,
					   `elem_id` BIGINT NULL,
					   `elem_type` VARCHAR(1024) NULL,
					   `quantity` BIGINT NULL,
					   `password` VARCHAR(1024) NULL,
					   `fecha_hora` DATETIME NULL,
					   `title` VARCHAR(1024) NULL,
					   `description` VARCHAR(1024) NULL,
					   `visits` BIGINT NULL,
					   `tags` VARCHAR(1024) NULL,
					   `sellers_tags` VARCHAR(1024) NULL,
					   `qr_path` VARCHAR(1024) NULL,
					   `invitation_id` BIGINT NULL,
					   `security_code` VARCHAR(1024) NULL,
					   `has_translation` BIGINT NULL,
					   `background` VARCHAR(1024) NULL,
					   `qr_text` VARCHAR(1024) NULL,
					   `active` BIGINT NULL,
					   `parameters` VARCHAR(2048) NULL,
					   `trial_version` BIGINT NULL,
					   `expiry_trial_date` DATETIME NULL,
					   `expiry_date` DATETIME NULL,
					   `activation_date` DATETIME NULL,
					   `product_type` VARCHAR(1024) NULL,
					   `custom_billing` BIGINT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;